/*
 * The MIT License
 *
 * Copyright 2014 Tiago.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.au.gui;

import com.au.gui.listener.RecuperarSenhaActionListener;
import com.au.util.LimitaDigitos;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Tiago
 */
public class TelaCriarNovaSenha extends javax.swing.JDialog {
    private final RecuperarSenhaActionListener listener;

    /**
     * Creates new form TelaRecuperarSenha
     */
    public TelaCriarNovaSenha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        campoConfirmacaoNovaSenha.setDocument(new LimitaDigitos((64), ""));
        campoCpfFuncionario.setDocument(new LimitaDigitos((15), "[^0-9\\.-]"));
        campoNovaSenha.setDocument(new LimitaDigitos((64), ""));
        listener = new RecuperarSenhaActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        textoCriarNovaSenha = new javax.swing.JLabel();
        textoNaoEPossivelRecuperarSenhaAntiga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        painelDadosFuncionario = new javax.swing.JPanel();
        textoCpfFuncionario = new javax.swing.JLabel();
        campoCpfFuncionario = new javax.swing.JTextField();
        campoCpfFuncionario.setActionCommand("CPF");
        textoDigiteNovaSenha = new javax.swing.JLabel();
        textoConfirmeNovaSenha = new javax.swing.JLabel();
        campoNovaSenha = new javax.swing.JPasswordField();
        campoConfirmacaoNovaSenha = new javax.swing.JPasswordField();
        botaoCriarNovaSenha = new javax.swing.JButton();
        botaoCancelarNovaSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoCriarNovaSenha.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        textoCriarNovaSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCriarNovaSenha.setText("Criar Nova Senha");

        textoNaoEPossivelRecuperarSenhaAntiga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textoNaoEPossivelRecuperarSenhaAntiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoNaoEPossivelRecuperarSenhaAntiga.setText("Devido à maneira como a senha é armazenada, não é possível recuperar a senha antiga.");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preencha as informações abaixo para criar uma nova senha.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCriarNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoNaoEPossivelRecuperarSenhaAntiga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoCriarNovaSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoNaoEPossivelRecuperarSenhaAntiga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        painelDadosFuncionario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados do Funcionário"));

        textoCpfFuncionario.setText("CPF do Funcionário:");

        campoCpfFuncionario.setNextFocusableComponent(campoNovaSenha);
        campoCpfFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoCpfFuncionarioFocusGained(evt);
            }
        });

        textoDigiteNovaSenha.setText("Digite a Nova Senha:");

        textoConfirmeNovaSenha.setText("Confirme a Nova Senha:");

        campoNovaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNovaSenhaFocusGained(evt);
            }
        });

        campoConfirmacaoNovaSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoConfirmacaoNovaSenhaFocusGained(evt);
            }
        });

        javax.swing.GroupLayout painelDadosFuncionarioLayout = new javax.swing.GroupLayout(painelDadosFuncionario);
        painelDadosFuncionario.setLayout(painelDadosFuncionarioLayout);
        painelDadosFuncionarioLayout.setHorizontalGroup(
            painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(textoCpfFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(campoCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(textoDigiteNovaSenha)
                        .addGap(18, 18, 18)
                        .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(painelDadosFuncionarioLayout.createSequentialGroup()
                        .addComponent(textoConfirmeNovaSenha)
                        .addGap(18, 18, 18)
                        .addComponent(campoConfirmacaoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDadosFuncionarioLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textoConfirmeNovaSenha, textoCpfFuncionario, textoDigiteNovaSenha});

        painelDadosFuncionarioLayout.setVerticalGroup(
            painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCpfFuncionario)
                    .addComponent(campoCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDigiteNovaSenha)
                    .addComponent(campoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoConfirmeNovaSenha)
                    .addComponent(campoConfirmacaoNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        botaoCriarNovaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/ok-32.png"))); // NOI18N
        botaoCriarNovaSenha.setText("Criar Nova Senha");
        botaoCriarNovaSenha.setNextFocusableComponent(botaoCancelarNovaSenha);

        botaoCancelarNovaSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaoCancelarNovaSenha.setText("Cancelar Criação de Nova Senha");
        botaoCancelarNovaSenha.setNextFocusableComponent(campoCpfFuncionario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoCancelarNovaSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCriarNovaSenha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDadosFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCriarNovaSenha)
                    .addComponent(botaoCancelarNovaSenha))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCpfFuncionarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFuncionarioFocusGained
        campoCpfFuncionario.selectAll();
    }//GEN-LAST:event_campoCpfFuncionarioFocusGained

    private void campoNovaSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNovaSenhaFocusGained
        campoNovaSenha.selectAll();
    }//GEN-LAST:event_campoNovaSenhaFocusGained

    private void campoConfirmacaoNovaSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoConfirmacaoNovaSenhaFocusGained
        campoConfirmacaoNovaSenha.selectAll();
    }//GEN-LAST:event_campoConfirmacaoNovaSenhaFocusGained

    public JButton getBotaoCancelarNovaSenha() {
        return botaoCancelarNovaSenha;
    }

    public void setBotaoCancelarNovaSenha(JButton botaoCancelarNovaSenha) {
        this.botaoCancelarNovaSenha = botaoCancelarNovaSenha;
    }

    public JButton getBotaoCriarNovaSenha() {
        return botaoCriarNovaSenha;
    }

    public void setBotaoCriarNovaSenha(JButton botaoCriarNovaSenha) {
        this.botaoCriarNovaSenha = botaoCriarNovaSenha;
    }

    public JPasswordField getCampoConfirmacaoNovaSenha() {
        return campoConfirmacaoNovaSenha;
    }

    public void setCampoConfirmacaoNovaSenha(JPasswordField campoConfirmacaoNovaSenha) {
        this.campoConfirmacaoNovaSenha = campoConfirmacaoNovaSenha;
    }

    public JTextField getCampoCpfFuncionario() {
        return campoCpfFuncionario;
    }

    public void setCampoCpfFuncionario(JTextField campoCpfFuncionario) {
        this.campoCpfFuncionario = campoCpfFuncionario;
    }

    public JPasswordField getCampoNovaSenha() {
        return campoNovaSenha;
    }

    public void setCampoNovaSenha(JPasswordField campoNovaSenha) {
        this.campoNovaSenha = campoNovaSenha;
    }

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarNovaSenha;
    private javax.swing.JButton botaoCriarNovaSenha;
    private javax.swing.JPasswordField campoConfirmacaoNovaSenha;
    private javax.swing.JTextField campoCpfFuncionario;
    private javax.swing.JPasswordField campoNovaSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel painelDadosFuncionario;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JLabel textoConfirmeNovaSenha;
    private javax.swing.JLabel textoCpfFuncionario;
    private javax.swing.JLabel textoCriarNovaSenha;
    private javax.swing.JLabel textoDigiteNovaSenha;
    private javax.swing.JLabel textoNaoEPossivelRecuperarSenhaAntiga;
    // End of variables declaration//GEN-END:variables
}
