/*
 * Copyright (C) 2014 tiago_000
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.au.gui;

import com.au.util.ManipulaConfigs;
import static com.au.util.ManipulaConfigs.getProp;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tiago_000
 */
public class TelaConfiguracoes extends javax.swing.JDialog {

    private Properties prop;
    private int modeloImpressoraCaixa;
    private int modeloImpressoraCozinha;
    private String interfaceImpressoraCaixa;
    private String interfaceImpressoraCozinha;
    private String enderecoImpressoraCaixa;
    private String enderecoImpressoraCozinha;
    private boolean ativarConsole;
    private boolean usarImpressoraCaixa;
    private boolean usarImpressoraCozinha;
    private boolean[] salvou = {false, false, false, false};

    /**
     * Creates new form TelaConfiguracoes
     */
    public TelaConfiguracoes() {
        initComponents();
        try {
            prop = getProp();
        } catch (IOException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        textoEnderecoCaixa.setEnabled(false);
        campoEnderecoCaixa.setEnabled(false);
        textoEnderecoCozinha.setEnabled(false);
        campoEnderecoCozinha.setEnabled(false);
        preencheCamposImpressora();
        preencheCamposDebug();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesCaixa = new javax.swing.ButtonGroup();
        grupoBotoesCozinha = new javax.swing.ButtonGroup();
        painelSuperior = new javax.swing.JPanel();
        textoIconeConfiguracoes = new javax.swing.JLabel();
        textoConfiguracoes = new javax.swing.JLabel();
        textoNaveguePelasAbas = new javax.swing.JLabel();
        painelComAbasGeral = new javax.swing.JTabbedPane();
        painelImpressoras = new javax.swing.JPanel();
        painelImpressoraCaixa = new javax.swing.JPanel();
        textoModeloCaixa = new javax.swing.JLabel();
        comboboxModeloCaixa = new javax.swing.JComboBox();
        textoInterfaceCaixa = new javax.swing.JLabel();
        botaoRadioParalelaCaixa = new javax.swing.JRadioButton();
        botaoRadioEthernetCaixa = new javax.swing.JRadioButton();
        textoEnderecoCaixa = new javax.swing.JLabel();
        campoEnderecoCaixa = new javax.swing.JTextField();
        checkboxAtivarImpressoraCaixa = new javax.swing.JCheckBox();
        botaoRadioUsbCaixa = new javax.swing.JRadioButton();
        painelImpressoraCozinha = new javax.swing.JPanel();
        botaoRadioEthernetCozinha = new javax.swing.JRadioButton();
        textoInterfaceCozinha = new javax.swing.JLabel();
        botaoRadioParalelaCozinha = new javax.swing.JRadioButton();
        textoModeloCozinha = new javax.swing.JLabel();
        comboboxModeloCozinha = new javax.swing.JComboBox();
        textoEnderecoCozinha = new javax.swing.JLabel();
        campoEnderecoCozinha = new javax.swing.JTextField();
        checkboxAtivarImpressoraCozinha = new javax.swing.JCheckBox();
        botaoRadioUsbCozinha = new javax.swing.JRadioButton();
        textoDefinaModelosEPortas = new javax.swing.JLabel();
        painelDebug = new javax.swing.JPanel();
        textoDefinaConfiguracoesDebug = new javax.swing.JLabel();
        checkboxIniciarConsole = new javax.swing.JCheckBox();
        textoParaFazerEfeito = new javax.swing.JLabel();
        botaoSalvarConfiguracoes = new javax.swing.JButton();
        botaCancelarConfiguracoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configurações - Sistema Pastelão");
        setMinimumSize(new java.awt.Dimension(644, 420));
        setResizable(false);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoIconeConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/settings-64.png"))); // NOI18N
        textoIconeConfiguracoes.setToolTipText("");

        textoConfiguracoes.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoConfiguracoes.setText("Configurações");

        textoNaveguePelasAbas.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        textoNaveguePelasAbas.setText("Navegue pelas abas abaixo para definir as configurações do sistema.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIconeConfiguracoes)
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoConfiguracoes)
                    .addComponent(textoNaveguePelasAbas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(textoConfiguracoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoNaveguePelasAbas))
                    .addComponent(textoIconeConfiguracoes))
                .addContainerGap())
        );

        painelComAbasGeral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        painelImpressoras.setName(""); // NOI18N

        painelImpressoraCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Caixa"));

        textoModeloCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoModeloCaixa.setText("Modelo:");

        comboboxModeloCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboboxModeloCaixa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o modelo", "MP-4000 TH", "MP-4200 TH" }));

        textoInterfaceCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoInterfaceCaixa.setText("Interface:");

        grupoBotoesCaixa.add(botaoRadioParalelaCaixa);
        botaoRadioParalelaCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioParalelaCaixa.setText("Paralela");

        grupoBotoesCaixa.add(botaoRadioEthernetCaixa);
        botaoRadioEthernetCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioEthernetCaixa.setText("Ethernet");

        textoEnderecoCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoEnderecoCaixa.setText("Endereço IP:");

        campoEnderecoCaixa.setColumns(15);
        campoEnderecoCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        checkboxAtivarImpressoraCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        checkboxAtivarImpressoraCaixa.setText("Ativar a impressora do Caixa");

        grupoBotoesCaixa.add(botaoRadioUsbCaixa);
        botaoRadioUsbCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioUsbCaixa.setText("USB");

        javax.swing.GroupLayout painelImpressoraCaixaLayout = new javax.swing.GroupLayout(painelImpressoraCaixa);
        painelImpressoraCaixa.setLayout(painelImpressoraCaixaLayout);
        painelImpressoraCaixaLayout.setHorizontalGroup(
            painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImpressoraCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelImpressoraCaixaLayout.createSequentialGroup()
                        .addComponent(textoModeloCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxModeloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxAtivarImpressoraCaixa)
                    .addGroup(painelImpressoraCaixaLayout.createSequentialGroup()
                        .addComponent(textoInterfaceCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRadioEthernetCaixa)
                        .addGap(2, 2, 2)
                        .addComponent(botaoRadioParalelaCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRadioUsbCaixa))
                    .addGroup(painelImpressoraCaixaLayout.createSequentialGroup()
                        .addComponent(textoEnderecoCaixa)
                        .addGap(18, 18, 18)
                        .addComponent(campoEnderecoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelImpressoraCaixaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textoEnderecoCaixa, textoInterfaceCaixa, textoModeloCaixa});

        painelImpressoraCaixaLayout.setVerticalGroup(
            painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImpressoraCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxAtivarImpressoraCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoModeloCaixa)
                    .addComponent(comboboxModeloCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoInterfaceCaixa)
                        .addComponent(botaoRadioEthernetCaixa))
                    .addComponent(botaoRadioUsbCaixa)
                    .addComponent(botaoRadioParalelaCaixa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEnderecoCaixa)
                    .addComponent(campoEnderecoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelImpressoraCozinha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cozinha"));

        grupoBotoesCozinha.add(botaoRadioEthernetCozinha);
        botaoRadioEthernetCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioEthernetCozinha.setText("Ethernet");

        textoInterfaceCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoInterfaceCozinha.setText("Interface:");

        grupoBotoesCozinha.add(botaoRadioParalelaCozinha);
        botaoRadioParalelaCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioParalelaCozinha.setText("Paralela");

        textoModeloCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoModeloCozinha.setText("Modelo:");

        comboboxModeloCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        comboboxModeloCozinha.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione o modelo", "MP-4000 TH", "MP-4200 TH" }));

        textoEnderecoCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoEnderecoCozinha.setText("Endereço IP:");

        campoEnderecoCozinha.setColumns(15);
        campoEnderecoCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoEnderecoCozinha.setMinimumSize(new java.awt.Dimension(6, 25));

        checkboxAtivarImpressoraCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        checkboxAtivarImpressoraCozinha.setText("Ativar a impressora da Cozinha");

        grupoBotoesCozinha.add(botaoRadioUsbCozinha);
        botaoRadioUsbCozinha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoRadioUsbCozinha.setText("USB");

        javax.swing.GroupLayout painelImpressoraCozinhaLayout = new javax.swing.GroupLayout(painelImpressoraCozinha);
        painelImpressoraCozinha.setLayout(painelImpressoraCozinhaLayout);
        painelImpressoraCozinhaLayout.setHorizontalGroup(
            painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImpressoraCozinhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelImpressoraCozinhaLayout.createSequentialGroup()
                        .addComponent(textoInterfaceCozinha)
                        .addGap(18, 18, 18)
                        .addComponent(botaoRadioEthernetCozinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRadioParalelaCozinha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoRadioUsbCozinha))
                    .addGroup(painelImpressoraCozinhaLayout.createSequentialGroup()
                        .addComponent(textoModeloCozinha)
                        .addGap(18, 18, 18)
                        .addComponent(comboboxModeloCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(checkboxAtivarImpressoraCozinha)
                    .addGroup(painelImpressoraCozinhaLayout.createSequentialGroup()
                        .addComponent(textoEnderecoCozinha)
                        .addGap(18, 18, 18)
                        .addComponent(campoEnderecoCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelImpressoraCozinhaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textoEnderecoCozinha, textoInterfaceCozinha, textoModeloCozinha});

        painelImpressoraCozinhaLayout.setVerticalGroup(
            painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImpressoraCozinhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkboxAtivarImpressoraCozinha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoModeloCozinha)
                    .addComponent(comboboxModeloCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoInterfaceCozinha)
                    .addComponent(botaoRadioEthernetCozinha)
                    .addComponent(botaoRadioParalelaCozinha)
                    .addComponent(botaoRadioUsbCozinha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelImpressoraCozinhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoEnderecoCozinha)
                    .addComponent(campoEnderecoCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textoDefinaModelosEPortas.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoDefinaModelosEPortas.setText("Defina abaixo os modelos e portas das impressoras do sistema:");

        javax.swing.GroupLayout painelImpressorasLayout = new javax.swing.GroupLayout(painelImpressoras);
        painelImpressoras.setLayout(painelImpressorasLayout);
        painelImpressorasLayout.setHorizontalGroup(
            painelImpressorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelImpressorasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelImpressorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDefinaModelosEPortas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelImpressorasLayout.createSequentialGroup()
                        .addComponent(painelImpressoraCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelImpressoraCozinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelImpressorasLayout.setVerticalGroup(
            painelImpressorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelImpressorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoDefinaModelosEPortas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelImpressorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelImpressoraCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelImpressoraCozinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelComAbasGeral.addTab("<html><font size=4><b>Impressoras", new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/check-26.png")), painelImpressoras); // NOI18N

        textoDefinaConfiguracoesDebug.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoDefinaConfiguracoesDebug.setText("Defina abaixo as configurações para debugar o sistema:");

        checkboxIniciarConsole.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkboxIniciarConsole.setText("Ativar Console ao iniciar o sistema");

        textoParaFazerEfeito.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        textoParaFazerEfeito.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoParaFazerEfeito.setText("Para estas alterações fazerem efeito, é necessário fechar e abrir novamente o sistema");

        javax.swing.GroupLayout painelDebugLayout = new javax.swing.GroupLayout(painelDebug);
        painelDebug.setLayout(painelDebugLayout);
        painelDebugLayout.setHorizontalGroup(
            painelDebugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDebugLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDebugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDebugLayout.createSequentialGroup()
                        .addComponent(checkboxIniciarConsole)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(textoParaFazerEfeito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoDefinaConfiguracoesDebug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelDebugLayout.setVerticalGroup(
            painelDebugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDebugLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoDefinaConfiguracoesDebug)
                .addGap(18, 18, 18)
                .addComponent(checkboxIniciarConsole)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(textoParaFazerEfeito)
                .addContainerGap())
        );

        painelComAbasGeral.addTab("<html><font size=4><b>Debug", new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/monitor-26.png")), painelDebug); // NOI18N

        botaoSalvarConfiguracoes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoSalvarConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/ok-32.png"))); // NOI18N
        botaoSalvarConfiguracoes.setText("Salvar Alterações nas Configurações");
        botaoSalvarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarConfiguracoesActionPerformed(evt);
            }
        });

        botaCancelarConfiguracoes.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaCancelarConfiguracoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaCancelarConfiguracoes.setText("Cancelar Alterações nas Configurações");
        botaCancelarConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaCancelarConfiguracoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaCancelarConfiguracoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoSalvarConfiguracoes))
                    .addComponent(painelComAbasGeral))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelComAbasGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvarConfiguracoes)
                    .addComponent(botaCancelarConfiguracoes))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(757, 459));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void preencheCamposImpressora() {
        //Recuperando configurações do arquivo para as variáveis;
        usarImpressoraCaixa = Boolean.parseBoolean(prop.getProperty("prop.impressora.caixa.ativa"));
        usarImpressoraCozinha = Boolean.parseBoolean(prop.getProperty("prop.impressora.cozinha.ativa"));

        modeloImpressoraCaixa = Integer.parseInt(prop.getProperty("prop.impressora.caixa.modelo"));
        modeloImpressoraCozinha = Integer.parseInt(prop.getProperty("prop.impressora.cozinha.modelo"));

        interfaceImpressoraCaixa = prop.getProperty("prop.impressora.caixa.interface");
        interfaceImpressoraCozinha = prop.getProperty("prop.impressora.cozinha.interface");

        enderecoImpressoraCaixa = prop.getProperty("prop.impressora.caixa.endereco");
        enderecoImpressoraCozinha = prop.getProperty("prop.impressora.cozinha.endereco");

        //Definindo e verificando quais impressoras estão ativas
        checkboxAtivarImpressoraCaixa.setSelected(usarImpressoraCaixa);
        checkboxAtivarImpressoraCozinha.setSelected(usarImpressoraCozinha);

        //Desativando os campos caso as impressoras não estejam ativadas
        if (!usarImpressoraCaixa) {
            textoModeloCaixa.setEnabled(false);
            comboboxModeloCaixa.setEnabled(false);
            textoInterfaceCaixa.setEnabled(false);
            botaoRadioEthernetCaixa.setEnabled(false);
            botaoRadioParalelaCaixa.setEnabled(false);
            botaoRadioUsbCaixa.setEnabled(false);
            textoEnderecoCaixa.setEnabled(false);
            campoEnderecoCaixa.setEnabled(false);
        }
        if (!usarImpressoraCozinha) {
            textoModeloCozinha.setEnabled(false);
            comboboxModeloCozinha.setEnabled(false);
            textoInterfaceCozinha.setEnabled(false);
            botaoRadioEthernetCozinha.setEnabled(false);
            botaoRadioParalelaCozinha.setEnabled(false);
            botaoRadioUsbCozinha.setEnabled(false);
            textoEnderecoCozinha.setEnabled(false);
            campoEnderecoCozinha.setEnabled(false);
        }
        checkboxAtivarImpressoraCaixa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean estaSelecionado = checkboxAtivarImpressoraCaixa.isSelected();
                textoModeloCaixa.setEnabled(estaSelecionado);
                comboboxModeloCaixa.setEnabled(estaSelecionado);
                textoInterfaceCaixa.setEnabled(estaSelecionado);
                botaoRadioEthernetCaixa.setEnabled(estaSelecionado);
                botaoRadioParalelaCaixa.setEnabled(estaSelecionado);
                botaoRadioUsbCaixa.setEnabled(estaSelecionado);
                if (botaoRadioEthernetCaixa.isSelected()) {
                    textoEnderecoCaixa.setEnabled(estaSelecionado);
                    campoEnderecoCaixa.setEnabled(estaSelecionado);
                    if (interfaceImpressoraCaixa.equals("ethernet")) {
                        campoEnderecoCaixa.setText(enderecoImpressoraCaixa);
                    }
                }
                //textoEnderecoCaixa.setEnabled(estaSelecionado);
                //campoEnderecoCaixa.setEnabled(estaSelecionado);
            }
        });
        checkboxAtivarImpressoraCozinha.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean estaSelecionado = checkboxAtivarImpressoraCozinha.isSelected();
                textoModeloCozinha.setEnabled(estaSelecionado);
                comboboxModeloCozinha.setEnabled(estaSelecionado);
                textoInterfaceCozinha.setEnabled(estaSelecionado);
                botaoRadioEthernetCozinha.setEnabled(estaSelecionado);
                botaoRadioParalelaCozinha.setEnabled(estaSelecionado);
                botaoRadioUsbCozinha.setEnabled(estaSelecionado);
                if (botaoRadioEthernetCozinha.isSelected()) {
                    textoEnderecoCozinha.setEnabled(estaSelecionado);
                    campoEnderecoCozinha.setEnabled(estaSelecionado);
                    if (interfaceImpressoraCozinha.equals("ethernet")) {
                        campoEnderecoCozinha.setText(enderecoImpressoraCozinha);
                    }
                }
            }
        });

        //Configurando a opção selecionada na Combo Box
        switch (modeloImpressoraCaixa) {
            case 5:
                comboboxModeloCaixa.setSelectedIndex(1);
                break;
            case 7:
                comboboxModeloCaixa.setSelectedIndex(2);
                break;
            default:
                comboboxModeloCaixa.setSelectedIndex(0);
        }
        switch (modeloImpressoraCozinha) {
            case 5:
                comboboxModeloCozinha.setSelectedIndex(1);
                break;
            case 7:
                comboboxModeloCozinha.setSelectedIndex(2);
                break;
            default:
                comboboxModeloCozinha.setSelectedIndex(0);
        }

        //Configurando qual RadioButton iniciará selecionado
        switch (interfaceImpressoraCaixa) {
            case "ethernet":
                botaoRadioEthernetCaixa.setSelected(true);
                break;
            case "paralela":
                botaoRadioParalelaCaixa.setSelected(true);
                break;
            case "usb":
                botaoRadioUsbCaixa.setSelected(true);
                break;
            default:
                grupoBotoesCaixa.clearSelection();
        }
        switch (interfaceImpressoraCozinha) {
            case "ethernet":
                botaoRadioEthernetCozinha.setSelected(true);
                break;
            case "paralela":
                botaoRadioParalelaCozinha.setSelected(true);
                break;
            case "usb":
                botaoRadioUsbCozinha.setSelected(true);
                break;
            default:
                grupoBotoesCozinha.clearSelection();
        }

        //Ativa o texto e campo de endereço no caso da opção Ethernet ser selecionada, bem como colocar o valor do endereço no campo
        if (botaoRadioEthernetCaixa.isSelected()) {
            if (usarImpressoraCaixa) {
                textoEnderecoCaixa.setEnabled(true);
                campoEnderecoCaixa.setEnabled(true);
                campoEnderecoCaixa.setText(enderecoImpressoraCaixa);
            }
        }
        if (botaoRadioEthernetCozinha.isSelected()) {
            if (usarImpressoraCozinha) {
                textoEnderecoCozinha.setEnabled(true);
                campoEnderecoCozinha.setEnabled(true);
                campoEnderecoCozinha.setText(enderecoImpressoraCozinha);
            }
        }

        //Configurando se o texto e campo de Endereço serão ativos (eles são ativos no caso da opção "Ethernet" estiver selecionada
        botaoRadioEthernetCaixa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCaixa.setEnabled(true);
                campoEnderecoCaixa.setEnabled(true);
            }
        });
        botaoRadioParalelaCaixa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCaixa.setEnabled(false);
                campoEnderecoCaixa.setEnabled(false);
            }
        });
        botaoRadioUsbCaixa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCaixa.setEnabled(false);
                campoEnderecoCaixa.setEnabled(false);
            }
        });
        botaoRadioEthernetCozinha.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCozinha.setEnabled(true);
                campoEnderecoCozinha.setEnabled(true);
            }
        });
        botaoRadioParalelaCozinha.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCozinha.setEnabled(false);
                campoEnderecoCozinha.setEnabled(false);
            }
        });
        botaoRadioUsbCozinha.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                textoEnderecoCozinha.setEnabled(false);
                campoEnderecoCozinha.setEnabled(false);
            }
        });
    }

    private void preencheCamposDebug() {
        ativarConsole = Boolean.parseBoolean(prop.getProperty("prop.debug.console"));
        if (ativarConsole) {
            checkboxIniciarConsole.setSelected(true);
        }
    }

    private boolean salvarConfigsImpressoraCaixa() {
        System.out.println("Configurando Impressora do Caixa:");
        usarImpressoraCaixa = checkboxAtivarImpressoraCaixa.isSelected();
        System.out.println("Usar impressora do caixa: " +usarImpressoraCaixa);
        switch (comboboxModeloCaixa.getSelectedIndex()) {
            case 0:
                System.out.println("A opção selecionada é inválida!");
                return false;
            case 1:
                System.out.println("Modelo selecionado: MP-4000 TH");
                modeloImpressoraCaixa = 5;
                break;
            case 2:
                System.out.println("Modelo selecionado: MP-4200 TH");
                modeloImpressoraCaixa = 7;
                break;
            default:
                System.out.println("Erro ao selecionar o modelo da impressora");
                return false;
        }
        if (botaoRadioEthernetCaixa.isSelected()){
            interfaceImpressoraCaixa = "ethernet";
                enderecoImpressoraCaixa = campoEnderecoCaixa.getText();
                System.out.println("Interface selecionada: Ethernet");
                System.out.println("Endereço IP: " + campoEnderecoCaixa.getText());
        } else if (botaoRadioParalelaCaixa.isSelected()){
            interfaceImpressoraCaixa = "paralela";
                enderecoImpressoraCaixa = "LPT1";
                System.out.println("Interface selecionada: Paralela");
        } else if (botaoRadioUsbCaixa.isSelected()){
            interfaceImpressoraCaixa = "usb";
                enderecoImpressoraCaixa = "USB";
                System.out.println("Interface selecionada: USB");
        }
        try {
            salvou[0] = ManipulaConfigs.setProp("prop.impressora.caixa.ativa", String.valueOf(usarImpressoraCaixa));
            salvou[1] = ManipulaConfigs.setProp("prop.impressora.caixa.modelo", String.valueOf(modeloImpressoraCaixa));
            salvou[2] = ManipulaConfigs.setProp("prop.impressora.caixa.interface", interfaceImpressoraCaixa);
            salvou[3] = ManipulaConfigs.setProp("prop.impressora.caixa.endereco", enderecoImpressoraCaixa);
        } catch (IOException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < 4; i++) {
            if (salvou[i] == false) {
                return false;
            }
        }
        System.out.println("---------------------------------------------\n");
        return true;
    }

    private boolean salvarConfigsImpressoraCozinha() {
        System.out.println("Configurando Impressora da Cozinha:");
        usarImpressoraCozinha = checkboxAtivarImpressoraCozinha.isSelected();
        System.out.println("Usar impressora da cozinha: "+usarImpressoraCozinha);
        switch (comboboxModeloCozinha.getSelectedIndex()) {
            case 0:
                System.out.println("A opção selecionada é inválida!");
                return false;
            case 1:
                System.out.println("Modelo selecionado: MP-4000 TH");
                modeloImpressoraCozinha = 5;
                break;
            case 2:
                System.out.println("Modelo selecionado: MP-4200 TH");
                modeloImpressoraCozinha = 7;
                break;
            default:
                System.out.println("Erro ao selecionar o modelo da impressora");
                return false;
        }
        if (botaoRadioEthernetCozinha.isSelected()){
            interfaceImpressoraCozinha = "ethernet";
                enderecoImpressoraCozinha = campoEnderecoCozinha.getText();
                System.out.println("Interface selecionada: Ethernet");
                System.out.println("Endereço IP: " + campoEnderecoCozinha.getText());
        } else if (botaoRadioParalelaCozinha.isSelected()){
            interfaceImpressoraCozinha = "paralela";
                enderecoImpressoraCozinha = "LPT1";
                System.out.println("Interface selecionada: Paralela");
        } else if (botaoRadioUsbCozinha.isSelected()){
            interfaceImpressoraCozinha = "usb";
                enderecoImpressoraCozinha = "USB";
                System.out.println("Interface selecionada: USB");
        }
        try {
            salvou[0] = ManipulaConfigs.setProp("prop.impressora.cozinha.ativa", String.valueOf(usarImpressoraCozinha));
            salvou[1] = ManipulaConfigs.setProp("prop.impressora.cozinha.modelo", String.valueOf(modeloImpressoraCozinha));
            salvou[2] = ManipulaConfigs.setProp("prop.impressora.cozinha.interface", interfaceImpressoraCozinha);
            salvou[3] = ManipulaConfigs.setProp("prop.impressora.cozinha.endereco", enderecoImpressoraCozinha);
        } catch (IOException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < 4; i++) {
            if (salvou[i] == false) {
                return false;
            }
        }
        System.out.println("---------------------------------------------");
        return true;
    }

    private boolean salvarConfigsDebug() {
        try {
            boolean saveProp = ManipulaConfigs.setProp("prop.debug.console", String.valueOf(checkboxIniciarConsole.isSelected()));
            System.out.println("---------------------------------------------");
            System.out.println("O console agora foi configurado para: " + getProp().getProperty("prop.debug.console")); //A configuração é buscada diretamente do arquivo de conf para verificar se foi mesmo alterada
            System.out.println("---------------------------------------------");
            return saveProp;
        } catch (IOException ex) {
            Logger.getLogger(TelaConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

    private void botaCancelarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaCancelarConfiguracoesActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaCancelarConfiguracoesActionPerformed

    private void botaoSalvarConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarConfiguracoesActionPerformed
        // VERIFICAR E SALVAR AS CONFIGS, no momento apenas a config do console está sendo salva
        if (salvarConfigsDebug() && salvarConfigsImpressoraCaixa() && salvarConfigsImpressoraCozinha()) {
            System.out.println("As configurações foram salvas com sucesso!");
            this.dispose();
        } else {
            System.out.println("Houve erro ao salvar as Configurações");
        }
    }//GEN-LAST:event_botaoSalvarConfiguracoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaCancelarConfiguracoes;
    private javax.swing.JRadioButton botaoRadioEthernetCaixa;
    private javax.swing.JRadioButton botaoRadioEthernetCozinha;
    private javax.swing.JRadioButton botaoRadioParalelaCaixa;
    private javax.swing.JRadioButton botaoRadioParalelaCozinha;
    private javax.swing.JRadioButton botaoRadioUsbCaixa;
    private javax.swing.JRadioButton botaoRadioUsbCozinha;
    private javax.swing.JButton botaoSalvarConfiguracoes;
    private javax.swing.JTextField campoEnderecoCaixa;
    private javax.swing.JTextField campoEnderecoCozinha;
    private javax.swing.JCheckBox checkboxAtivarImpressoraCaixa;
    private javax.swing.JCheckBox checkboxAtivarImpressoraCozinha;
    private javax.swing.JCheckBox checkboxIniciarConsole;
    private javax.swing.JComboBox comboboxModeloCaixa;
    private javax.swing.JComboBox comboboxModeloCozinha;
    private javax.swing.ButtonGroup grupoBotoesCaixa;
    private javax.swing.ButtonGroup grupoBotoesCozinha;
    private javax.swing.JTabbedPane painelComAbasGeral;
    private javax.swing.JPanel painelDebug;
    private javax.swing.JPanel painelImpressoraCaixa;
    private javax.swing.JPanel painelImpressoraCozinha;
    private javax.swing.JPanel painelImpressoras;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JLabel textoConfiguracoes;
    private javax.swing.JLabel textoDefinaConfiguracoesDebug;
    private javax.swing.JLabel textoDefinaModelosEPortas;
    private javax.swing.JLabel textoEnderecoCaixa;
    private javax.swing.JLabel textoEnderecoCozinha;
    private javax.swing.JLabel textoIconeConfiguracoes;
    private javax.swing.JLabel textoInterfaceCaixa;
    private javax.swing.JLabel textoInterfaceCozinha;
    private javax.swing.JLabel textoModeloCaixa;
    private javax.swing.JLabel textoModeloCozinha;
    private javax.swing.JLabel textoNaveguePelasAbas;
    private javax.swing.JLabel textoParaFazerEfeito;
    // End of variables declaration//GEN-END:variables
}
