/*
 * The MIT License
 *
 * Copyright 2014 tiago_000.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.au.gui;

import com.au.bean.Funcionario;
import com.au.dao.FuncionarioDao;
import java.awt.Color;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author tiago_000
 */
public class TelaCadastrarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastrarUsuario
     */
    public TelaCadastrarUsuario() {
        initComponents();
        campoNome.setDocument(new LimitaDigitos((250), "[^a-z|^A-Z|^ |^~]"));
        campoNascAno.setDocument(new LimitaDigitos((4), "[^0-9]"));
        campoNascMes.setDocument(new LimitaDigitos((2), "[^0-9]"));
        campoNascDia.setDocument(new LimitaDigitos((2), "[^0-9]"));
        campoRg.setDocument(new LimitaDigitos((15), "[^0-9|^.|^a-z|^A-Z\\-]"));
        campoEmail.setDocument(new LimitaDigitos((150), "[^0-9|^.|^_|^@|^a-z|^A-Z\\-]"));
        campoCelular.setDocument(new LimitaDigitos((15), "[^0-9|^()\\-]"));
        campoTelefone.setDocument(new LimitaDigitos((15), "[^0-9|^()\\-]"));
        campoAdmAno.setDocument(new LimitaDigitos((4), "[^0-9]"));
        campoAdmMes.setDocument(new LimitaDigitos((2), "[^0-9]"));
        campoAdmDia.setDocument(new LimitaDigitos((2), "[^0-9]"));
        campoSalario.setDocument(new LimitaDigitos((7), "[^0-9|^.]"));
        campoUser.setDocument(new LimitaDigitos((50), "[^0-9|^.|^a-z|^A-Z|^_\\-]"));
        campoPass.setDocument(new LimitaDigitos((50), "[^0-9|^a-z|^A-Z]"));
        campoPass2.setDocument(new LimitaDigitos((50), "[^0-9|^a-z|^A-Z]"));
        campoNome.requestFocus();

    }
    int validaForm[] = new int[]{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
    Border border2 = BorderFactory.createLineBorder(Color.gray, 1);
    Border border = BorderFactory.createLineBorder(Color.red, 1);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        textoAdicionarUsuario = new javax.swing.JLabel();
        textoIconeNovoUsuario = new javax.swing.JLabel();
        textoPreencherDados = new javax.swing.JLabel();
        painelDadosPessoais = new javax.swing.JPanel();
        textoNome = new javax.swing.JLabel();
        textoDtNasc = new javax.swing.JLabel();
        textoSexo = new javax.swing.JLabel();
        textoRg = new javax.swing.JLabel();
        textoCpf = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        textoTelefone = new javax.swing.JLabel();
        textoCelular = new javax.swing.JLabel();
        caixaSelecaoSexo = new javax.swing.JComboBox();
        campoNome = new javax.swing.JTextField();
        campoRg = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        try{ 
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##"); 
            campoCpf = new javax.swing.JFormattedTextField(cpf); 
        } 
        catch (Exception e){ 
        }
        campoEmail = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();
        campoCelular = new javax.swing.JTextField();
        campoNascDia = new javax.swing.JTextField();
        campoNascMes = new javax.swing.JTextField();
        campoNascAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();
        campoUser = new javax.swing.JTextField();
        caixaSelecaoNivel = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        caixaSelecaoAtivo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        campoAdmMes = new javax.swing.JTextField();
        campoAdmDia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoAdmAno = new javax.swing.JTextField();
        botaoCadastrar = new javax.swing.JButton();
        campoPass = new javax.swing.JPasswordField();
        campoPass2 = new javax.swing.JPasswordField();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoAdicionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoAdicionarUsuario.setText("Adicionar Novo Usuário");

        textoIconeNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/add_user-64.png"))); // NOI18N

        textoPreencherDados.setText("Preencha os dados abaixo para adicionar um novo usuário.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIconeNovoUsuario)
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoAdicionarUsuario)
                    .addComponent(textoPreencherDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoIconeNovoUsuario)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(textoAdicionarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPreencherDados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDadosPessoais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais"));

        textoNome.setText("Nome Completo:");

        textoDtNasc.setText("Data de Nascimento:");

        textoSexo.setText("Sexo:");

        textoRg.setText("RG:");

        textoCpf.setText("CPF:");

        textoEmail.setText("E-mail:");

        textoTelefone.setText("Telefone:");

        textoCelular.setText("Celular:");

        caixaSelecaoSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Feminino", "Masculino" }));
        caixaSelecaoSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSelecaoSexoActionPerformed(evt);
            }
        });
        caixaSelecaoSexo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                caixaSelecaoSexoFocusLost(evt);
            }
        });

        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNomeFocusLost(evt);
            }
        });

        campoRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRgActionPerformed(evt);
            }
        });
        campoRg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoRgFocusLost(evt);
            }
        });

        campoCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCpfActionPerformed(evt);
            }
        });
        campoCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCpfFocusLost(evt);
            }
        });

        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        campoEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoEmailFocusLost(evt);
            }
        });

        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        campoTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoTelefoneFocusLost(evt);
            }
        });

        campoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCelularActionPerformed(evt);
            }
        });
        campoCelular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCelularFocusLost(evt);
            }
        });

        campoNascDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNascDiaActionPerformed(evt);
            }
        });
        campoNascDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNascDiaFocusLost(evt);
            }
        });

        campoNascMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNascMesActionPerformed(evt);
            }
        });
        campoNascMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNascMesFocusLost(evt);
            }
        });

        campoNascAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNascAnoActionPerformed(evt);
            }
        });
        campoNascAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoNascAnoFocusLost(evt);
            }
        });

        jLabel4.setText("/");

        jLabel5.setText("/");

        javax.swing.GroupLayout painelDadosPessoaisLayout = new javax.swing.GroupLayout(painelDadosPessoais);
        painelDadosPessoais.setLayout(painelDadosPessoaisLayout);
        painelDadosPessoaisLayout.setHorizontalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDtNasc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textoTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(textoEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoRg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 24, Short.MAX_VALUE))
                    .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                        .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(caixaSelecaoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(campoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(campoTelefone)
                                .addComponent(campoEmail)
                                .addComponent(campoCpf)
                                .addComponent(campoRg))
                            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                                .addComponent(campoNascDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNascMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoNascAno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelDadosPessoaisLayout.setVerticalGroup(
            painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosPessoaisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDtNasc)
                    .addComponent(campoNascDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNascMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNascAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSexo)
                    .addComponent(caixaSelecaoSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoRg)
                    .addComponent(campoRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCpf)
                    .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoEmail)
                    .addComponent(campoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoTelefone)
                    .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDadosPessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCelular)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados \"Funcionais\""));

        jLabel9.setText("Nome de Usuário:");

        jLabel10.setText("Senha:");

        jLabel11.setText("Redigite a Senha:");

        jLabel12.setText("Data de Admissão:");

        jLabel1.setText("Salário:");

        jLabel2.setText("Nivel:");

        campoSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSalarioActionPerformed(evt);
            }
        });
        campoSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSalarioFocusLost(evt);
            }
        });

        campoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUserActionPerformed(evt);
            }
        });
        campoUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUserFocusLost(evt);
            }
        });

        caixaSelecaoNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Funcionário", "Administrador" }));
        caixaSelecaoNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSelecaoNivelActionPerformed(evt);
            }
        });
        caixaSelecaoNivel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                caixaSelecaoNivelFocusLost(evt);
            }
        });

        jLabel3.setText("Ativo");

        caixaSelecaoAtivo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione", "Sim", "Não" }));
        caixaSelecaoAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaSelecaoAtivoActionPerformed(evt);
            }
        });
        caixaSelecaoAtivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                caixaSelecaoAtivoFocusLost(evt);
            }
        });

        jLabel8.setText("/");

        campoAdmMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAdmMesActionPerformed(evt);
            }
        });
        campoAdmMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAdmMesFocusLost(evt);
            }
        });

        campoAdmDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAdmDiaActionPerformed(evt);
            }
        });
        campoAdmDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAdmDiaFocusLost(evt);
            }
        });

        jLabel13.setText("/");

        campoAdmAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAdmAnoActionPerformed(evt);
            }
        });
        campoAdmAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoAdmAnoFocusLost(evt);
            }
        });

        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        campoPass.setText("jPasswordField1");
        campoPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPassActionPerformed(evt);
            }
        });
        campoPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPassFocusLost(evt);
            }
        });

        campoPass2.setText("jPasswordField2");
        campoPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPass2ActionPerformed(evt);
            }
        });
        campoPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoPass2FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoCadastrar))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoUser)
                            .addComponent(campoSalario)
                            .addComponent(campoPass)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(caixaSelecaoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(caixaSelecaoAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(campoAdmDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoAdmMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoAdmAno, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 129, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(campoPass2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoAdmDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAdmMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAdmAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(campoPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaSelecaoNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(caixaSelecaoAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCadastrar))
        );

        menuArquivo.setText("Arquivo");
        barraMenu.add(menuArquivo);

        menuEditar.setText("Editar");
        barraMenu.add(menuEditar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelDadosPessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosPessoais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        campoNascDia.requestFocus();
    }//GEN-LAST:event_campoNomeActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        campoCelular.requestFocus();
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void caixaSelecaoSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSelecaoSexoActionPerformed
        campoRg.requestFocus();
    }//GEN-LAST:event_caixaSelecaoSexoActionPerformed
    private Date montaData(String ano, String mes, String dia) {
        String dataConcatenada = ano + "-" + mes + "-" + dia;
        System.out.println(dataConcatenada);
        DateFormat formataData = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date data;
        try {
            data = formataData.parse(dataConcatenada);
            java.sql.Date dataSql = new java.sql.Date(data.getTime());
            return dataSql;
        } catch (ParseException ex) {
            Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    private boolean validaCampos() {
        for (int i = 0; i < validaForm.length; i++) {
            if (validaForm[i] == 0) {
                return false;
            }
        }
        return true;
    }

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed

        if (validaCampos()) {
            Funcionario funcionario = new Funcionario();
            FuncionarioDao funcDao = new FuncionarioDao();

            funcionario.setNomeFunc(campoNome.getText());
            funcionario.setNascFunc(montaData(campoNascAno.getText(), campoNascMes.getText(), campoNascDia.getText()));
            if (caixaSelecaoSexo.getSelectedItem() == "Feminino") {
                funcionario.setSexoFunc("F");
            } else {
                funcionario.setSexoFunc("M");
            }
            funcionario.setRgFunc(campoRg.getText());
            funcionario.setCpfFunc(campoCpf.getText());
            funcionario.setMailFunc(campoEmail.getText());
            funcionario.setFoneFunc(campoTelefone.getText());
            funcionario.setCelFunc(campoCelular.getText());
            funcionario.setDtAdmFunc(montaData(campoAdmAno.getText(), campoAdmMes.getText(), campoAdmDia.getText()));
            funcionario.setSalFunc(Double.parseDouble(campoSalario.getText()));
            funcionario.setUserFunc(campoUser.getText());

            HexSha hexSha = new HexSha(String.valueOf(campoPass.getPassword()));
            funcionario.setPassFunc(hexSha.ConvertSha());

            if (caixaSelecaoNivel.getSelectedItem() == "Administrador") {
                funcionario.setNivelFunc(1);
            } else {
                funcionario.setNivelFunc(0);
            }
            if (caixaSelecaoAtivo.getSelectedItem() == "Sim") {
                funcionario.setEstaAtivo(true);
            } else {
                funcionario.setEstaAtivo(false);
            }

            funcDao.addFuncionario(funcionario);
        } else {
            Border border = BorderFactory.createLineBorder(Color.red, 1);
            if (validaForm[0] == 0) {
                campoNome.setBorder(border);
            }
            if (validaForm[1] == 0) {
                campoNascDia.setBorder(border);
            }
            if (validaForm[2] == 0) {
                campoNascMes.setBorder(border);
            }
            if (validaForm[3] == 0) {
                campoNascAno.setBorder(border);
            }
            if (validaForm[4] == 0) {
                caixaSelecaoSexo.setBorder(border);
            }
            if (validaForm[5] == 0) {
                campoRg.setBorder(border);
            }
            if (validaForm[6] == 0) {
                campoCpf.setBorder(border);
            }
            if (validaForm[7] == 0) {
                campoEmail.setBorder(border);
            }
            if (validaForm[8] == 0) {
                campoTelefone.setBorder(border);
            }
            if (validaForm[9] == 0) {
                campoCelular.setBorder(border);
            }
            if (validaForm[10] == 0) {
                campoAdmDia.setBorder(border);
            }
            if (validaForm[11] == 0) {
                campoAdmMes.setBorder(border);
            }
            if (validaForm[12] == 0) {
                campoAdmAno.setBorder(border);
            }
            if (validaForm[13] == 0) {
                campoSalario.setBorder(border);
            }
            if (validaForm[14] == 0) {
                campoUser.setBorder(border);
            }
            if (validaForm[15] == 0) {
                campoPass.setBorder(border);
            }
            if (validaForm[16] == 0) {
                campoPass2.setBorder(border);
            }
            if (validaForm[17] == 0) {
                caixaSelecaoNivel.setBorder(border);
            }
            if (validaForm[18] == 0) {
                caixaSelecaoAtivo.setBorder(border);
            }
        }


    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void campoPass2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPass2FocusLost
        String pass, pass2;

        pass = String.valueOf(campoPass.getPassword());
        pass2 = String.valueOf(campoPass2.getPassword());

        if (!String.valueOf(campoPass2.getPassword()).equals("")) {
            validaForm[16] = 1;
        } else {
            validaForm[16] = 0;
        }
        if (!pass.equals(pass2)) {
            campoPass2.setForeground(Color.red);
            validaForm[16] = 0;
        } else {
            campoPass2.setForeground(Color.black);
            campoPass2.setBorder(border2);
        }
    }//GEN-LAST:event_campoPass2FocusLost

    private void campoNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusLost
        if (!campoNome.getText().equals("")) {
            validaForm[0] = 1;
            campoNome.setBorder(border2);
        } else {
            validaForm[0] = 0;
        }
    }//GEN-LAST:event_campoNomeFocusLost

    private void campoNascDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNascDiaFocusLost
        if (!campoNascDia.getText().equals("")) {
            validaForm[1] = 1;
            campoNascDia.setBorder(border2);
        } else {
            validaForm[1] = 0;
        }
    }//GEN-LAST:event_campoNascDiaFocusLost

    private void campoNascMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNascMesFocusLost
        if (!campoNascMes.getText().equals("")) {
            validaForm[2] = 1;
            campoNascMes.setBorder(border2);
        } else {
            validaForm[2] = 0;
        }
    }//GEN-LAST:event_campoNascMesFocusLost

    private void campoNascAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNascAnoFocusLost
        if (!campoNascAno.getText().equals("")) {
            validaForm[3] = 1;
            campoNascAno.setBorder(border2);
        } else {
            validaForm[3] = 0;
        }
    }//GEN-LAST:event_campoNascAnoFocusLost

    private void caixaSelecaoSexoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecaoSexoFocusLost
        if (!caixaSelecaoSexo.getSelectedItem().equals("Selecione")) {
            validaForm[4] = 1;
            caixaSelecaoSexo.setBorder(border2);
        } else {
            validaForm[4] = 0;
        }
    }//GEN-LAST:event_caixaSelecaoSexoFocusLost

    private void campoRgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoRgFocusLost
        if (!campoRg.getText().equals("")) {
            validaForm[5] = 1;
            campoRg.setBorder(border2);
        } else {
            validaForm[5] = 0;
        }
    }//GEN-LAST:event_campoRgFocusLost

    private void campoCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCpfFocusLost
        if (!campoCpf.getText().equals("")) {
            validaForm[6] = 1;
            campoCpf.setBorder(border2);
        } else {
            validaForm[6] = 0;
        }
    }//GEN-LAST:event_campoCpfFocusLost

    private void campoEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoEmailFocusLost
        Pattern p = Pattern.compile(".+@.+\\.[a-z]+");
        Matcher m = p.matcher(campoEmail.getText());

        if (m.matches()) {//(!campoEmail.getText().equals("")) {
            validaForm[7] = 1;
            campoEmail.setBorder(border2);
        } else {
            campoEmail.setBorder(border);
            validaForm[7] = 0;
        }
    }//GEN-LAST:event_campoEmailFocusLost

    private void campoTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoTelefoneFocusLost
        if (!campoTelefone.getText().equals("")) {
            validaForm[8] = 1;
            campoTelefone.setBorder(border2);
        } else {
            validaForm[8] = 0;
        }
    }//GEN-LAST:event_campoTelefoneFocusLost

    private void campoCelularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCelularFocusLost
        if (!campoCelular.getText().equals("")) {
            validaForm[9] = 1;
            campoCelular.setBorder(border2);
        } else {
            validaForm[9] = 0;
        }
    }//GEN-LAST:event_campoCelularFocusLost

    private void campoAdmDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAdmDiaFocusLost
        if (!campoAdmDia.getText().equals("")) {
            validaForm[10] = 1;
            campoAdmDia.setBorder(border2);
        } else {
            validaForm[10] = 0;
        }
    }//GEN-LAST:event_campoAdmDiaFocusLost

    private void campoAdmMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAdmMesFocusLost
        if (!campoAdmMes.getText().equals("")) {
            validaForm[11] = 1;
            campoAdmMes.setBorder(border2);
        } else {
            validaForm[11] = 0;
        }
    }//GEN-LAST:event_campoAdmMesFocusLost

    private void campoAdmAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoAdmAnoFocusLost
        if (!campoAdmAno.getText().equals("")) {
            validaForm[12] = 1;
            campoAdmAno.setBorder(border2);
        } else {
            validaForm[12] = 0;
        }
    }//GEN-LAST:event_campoAdmAnoFocusLost

    private void campoSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSalarioFocusLost
        if (!campoSalario.getText().equals("")) {
            validaForm[13] = 1;
            campoSalario.setBorder(border2);
        } else {
            validaForm[13] = 0;
        }
    }//GEN-LAST:event_campoSalarioFocusLost

    private void campoUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUserFocusLost
        if (!campoUser.getText().equals("")) {
            validaForm[14] = 1;
            campoUser.setBorder(border2);
        } else {
            validaForm[14] = 0;
        }
    }//GEN-LAST:event_campoUserFocusLost

    private void campoPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPassFocusLost
        if (!String.valueOf(campoPass.getPassword()).equals("")) {
            validaForm[15] = 1;
            campoPass.setBorder(border2);
        } else {
            validaForm[15] = 0;
        }
    }//GEN-LAST:event_campoPassFocusLost

    private void caixaSelecaoNivelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecaoNivelFocusLost
        if (!caixaSelecaoNivel.getSelectedItem().equals("Selecione")) {
            validaForm[17] = 1;
            caixaSelecaoNivel.setBorder(border2);
        } else {
            validaForm[17] = 0;
        }
    }//GEN-LAST:event_caixaSelecaoNivelFocusLost

    private void caixaSelecaoAtivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_caixaSelecaoAtivoFocusLost
        if (!caixaSelecaoAtivo.getSelectedItem().equals("Selecione")) {
            validaForm[18] = 1;
            caixaSelecaoAtivo.setBorder(border2);
        } else {
            validaForm[18] = 0;
        }
    }//GEN-LAST:event_caixaSelecaoAtivoFocusLost

    private void campoNascDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNascDiaActionPerformed
        campoNascMes.requestFocus();
    }//GEN-LAST:event_campoNascDiaActionPerformed

    private void campoNascMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNascMesActionPerformed
        campoNascAno.requestFocus();
    }//GEN-LAST:event_campoNascMesActionPerformed

    private void campoRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRgActionPerformed
        campoCpf.requestFocus();
    }//GEN-LAST:event_campoRgActionPerformed

    private void campoCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCpfActionPerformed
        campoEmail.requestFocus();
    }//GEN-LAST:event_campoCpfActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        campoTelefone.requestFocus();
    }//GEN-LAST:event_campoEmailActionPerformed

    private void campoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCelularActionPerformed
        campoAdmDia.requestFocus();
    }//GEN-LAST:event_campoCelularActionPerformed

    private void campoAdmDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAdmDiaActionPerformed
        campoAdmMes.requestFocus();
    }//GEN-LAST:event_campoAdmDiaActionPerformed

    private void campoAdmMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAdmMesActionPerformed
        campoAdmAno.requestFocus();
    }//GEN-LAST:event_campoAdmMesActionPerformed

    private void campoAdmAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAdmAnoActionPerformed
        campoSalario.requestFocus();
    }//GEN-LAST:event_campoAdmAnoActionPerformed

    private void campoSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSalarioActionPerformed
        campoUser.requestFocus();
    }//GEN-LAST:event_campoSalarioActionPerformed

    private void campoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUserActionPerformed
        campoPass.requestFocus();
    }//GEN-LAST:event_campoUserActionPerformed

    private void campoPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPassActionPerformed
        campoPass2.requestFocus();
    }//GEN-LAST:event_campoPassActionPerformed

    private void campoPass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPass2ActionPerformed

    }//GEN-LAST:event_campoPass2ActionPerformed

    private void campoNascAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNascAnoActionPerformed

    }//GEN-LAST:event_campoNascAnoActionPerformed

    private void caixaSelecaoNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSelecaoNivelActionPerformed

    }//GEN-LAST:event_caixaSelecaoNivelActionPerformed

    private void caixaSelecaoAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaSelecaoAtivoActionPerformed

    }//GEN-LAST:event_caixaSelecaoAtivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JComboBox caixaSelecaoAtivo;
    private javax.swing.JComboBox caixaSelecaoNivel;
    private javax.swing.JComboBox caixaSelecaoSexo;
    private javax.swing.JTextField campoAdmAno;
    private javax.swing.JTextField campoAdmDia;
    private javax.swing.JTextField campoAdmMes;
    private javax.swing.JTextField campoCelular;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNascAno;
    private javax.swing.JTextField campoNascDia;
    private javax.swing.JTextField campoNascMes;
    private javax.swing.JTextField campoNome;
    private javax.swing.JPasswordField campoPass;
    private javax.swing.JPasswordField campoPass2;
    private javax.swing.JTextField campoRg;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JPanel painelDadosPessoais;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JLabel textoAdicionarUsuario;
    private javax.swing.JLabel textoCelular;
    private javax.swing.JLabel textoCpf;
    private javax.swing.JLabel textoDtNasc;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoIconeNovoUsuario;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoPreencherDados;
    private javax.swing.JLabel textoRg;
    private javax.swing.JLabel textoSexo;
    private javax.swing.JLabel textoTelefone;
    // End of variables declaration//GEN-END:variables
}
