/*
 * Copyright (C) 2014 BrunoRicardo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.au.gui;

import com.au.bean.Ingrediente;
import com.au.bean.Produto;
import com.au.bean.Receita;
import com.au.dao.IngredienteDao;
import com.au.dao.ProdutoDao;
import com.au.dao.ReceitaDao;
import com.au.util.LimitaDigitos;
import com.au.util.CustomComboBoxInt;
import com.au.gui.tmodel.ProdutoIngredientesTableModel;
import com.au.gui.tmodel.ProdutoTableModel;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author tiago_000
 */
public class TelaCadastrarProduto extends javax.swing.JDialog implements ListSelectionListener {

    private ProdutoTableModel tableModelProdutos;
    private ProdutoIngredientesTableModel tableModelIngredientes;
    private List<Ingrediente> ingredientes = new ArrayList<>();
    private final Border vermelha = new MatteBorder(1, 1, 1, 1, Color.red);
    private final Border normal;
    private Integer id = null;
    private final ProdutoDao pDao = new ProdutoDao();
    private final ReceitaDao rDao = new ReceitaDao();
    private final IngredienteDao iDao = new IngredienteDao();

    /**
     * Creates new form TelaCadastrarUsuario
     *
     * @param parent
     * @param modal
     */
    public TelaCadastrarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        textoErroIngrediente.setVisible(false);
        normal = campoNome.getBorder();
        inicializaTableModel();
        habilitaBotoesParaSalvar();
        campoNome.setDocument(new LimitaDigitos((250), "[^a-zA-Z À-ÄÈ-ËÌ-ÏÒ-ÖÙ-Üà-äè-ëì-ïò-öù-ü0-9\\-çÇ/_]"));
        campoValor.setDocument(new LimitaDigitos((7), "[^0-9\\.]"));
        campoBarras.setDocument(new LimitaDigitos((150), "[^0-9]"));
        campoPesquisarProduto.setDocument(new LimitaDigitos((250), "[^a-zA-Z À-ÄÈ-ËÌ-ÏÒ-ÖÙ-Üà-äè-ëì-ïò-öù-ü0-9\\-çÇ/_]"));
        tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(1000);
        tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(70);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelSuperior = new javax.swing.JPanel();
        textoAdicionarProduto = new javax.swing.JLabel();
        textoIconeNovoProduto = new javax.swing.JLabel();
        textoPreencherDados = new javax.swing.JLabel();
        painelAdicionarModificarProdutos = new javax.swing.JPanel();
        painelProdutoIndustrializado = new javax.swing.JPanel();
        textoBarras = new javax.swing.JLabel();
        campoBarras = new javax.swing.JTextField();
        painelProdutoPreparado = new javax.swing.JPanel();
        caixaSelecaoIng = new javax.swing.JComboBox(getIngs());
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaIngredientes = new javax.swing.JTable();
        botaoAdicionarIngrediente = new javax.swing.JButton();
        botaoRemoverIngrediente = new javax.swing.JButton();
        textoErroIngrediente = new javax.swing.JLabel();
        radioPrep = new javax.swing.JRadioButton();
        radioInd = new javax.swing.JRadioButton();
        textoTipo = new javax.swing.JLabel();
        textoValor = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        textoNome = new javax.swing.JLabel();
        textoCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        painelProcurarProdutos = new javax.swing.JPanel();
        textoCliqueParaEditar = new javax.swing.JLabel();
        textoProcurarProduto = new javax.swing.JLabel();
        campoPesquisarProduto = new javax.swing.JTextField();
        botaoProcurarProduto = new javax.swing.JButton();
        painelScrollTabela = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        painelBotoes = new javax.swing.JPanel();
        botaoCancelarCadastro = new javax.swing.JButton();
        botaoCadastrarProduto = new javax.swing.JButton();
        botaoLimparCampos = new javax.swing.JButton();
        botaoAtualizarProduto = new javax.swing.JButton();
        botaoExcluirProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar/Modificar Produto - Sistema Pastelão");

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoAdicionarProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoAdicionarProduto.setText("Adicionar Novo Produto");

        textoIconeNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/beer_glass-64.png"))); // NOI18N

        textoPreencherDados.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        textoPreencherDados.setText("Preencha os dados abaixo para adicionar um novo produto.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIconeNovoProduto)
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoAdicionarProduto)
                    .addComponent(textoPreencherDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoIconeNovoProduto)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(textoAdicionarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPreencherDados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelAdicionarModificarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adicionar/Modificar Produto"));

        painelProdutoIndustrializado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Industrializado")));

        textoBarras.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoBarras.setText("Código Barras");

        campoBarras.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoBarras.setEnabled(false);
        campoBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoBarrasFocusGained(evt);
            }
        });

        javax.swing.GroupLayout painelProdutoIndustrializadoLayout = new javax.swing.GroupLayout(painelProdutoIndustrializado);
        painelProdutoIndustrializado.setLayout(painelProdutoIndustrializadoLayout);
        painelProdutoIndustrializadoLayout.setHorizontalGroup(
            painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoIndustrializadoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(textoBarras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoBarras, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelProdutoIndustrializadoLayout.setVerticalGroup(
            painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoIndustrializadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBarras)
                    .addComponent(campoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        painelProdutoPreparado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Preparado"));

        caixaSelecaoIng.setEnabled(false);

        tabelaIngredientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição"
            }
        ));
        tabelaIngredientes.setEnabled(false);
        jScrollPane2.setViewportView(tabelaIngredientes);

        botaoAdicionarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/plus-26.png"))); // NOI18N
        botaoAdicionarIngrediente.setActionCommand("Adicionar Ingrediente");
        botaoAdicionarIngrediente.setEnabled(false);
        botaoAdicionarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarIngredienteActionPerformed(evt);
            }
        });

        botaoRemoverIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/minus-26.png"))); // NOI18N
        botaoRemoverIngrediente.setActionCommand("Remover Ingrediente");
        botaoRemoverIngrediente.setEnabled(false);
        botaoRemoverIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelProdutoPreparadoLayout = new javax.swing.GroupLayout(painelProdutoPreparado);
        painelProdutoPreparado.setLayout(painelProdutoPreparadoLayout);
        painelProdutoPreparadoLayout.setHorizontalGroup(
            painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(painelProdutoPreparadoLayout.createSequentialGroup()
                .addComponent(caixaSelecaoIng, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoAdicionarIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoRemoverIngrediente)
                .addContainerGap())
        );
        painelProdutoPreparadoLayout.setVerticalGroup(
            painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoPreparadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAdicionarIngrediente)
                    .addComponent(caixaSelecaoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoRemoverIngrediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        textoErroIngrediente.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoErroIngrediente.setForeground(new java.awt.Color(255, 0, 0));
        textoErroIngrediente.setText("Pelo menos 1 Ingrediente deve ser adicionado ao produto!");

        buttonGroup1.add(radioPrep);
        radioPrep.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        radioPrep.setText("Preparado");
        radioPrep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPrepActionPerformed(evt);
            }
        });

        buttonGroup1.add(radioInd);
        radioInd.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        radioInd.setText("Industrializado");
        radioInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIndActionPerformed(evt);
            }
        });

        textoTipo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoTipo.setText("Tipo Produto:");

        textoValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValor.setText("Valor Produto:");

        campoValor.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoValorFocusGained(evt);
            }
        });

        campoNome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoNomeFocusGained(evt);
            }
        });

        textoNome.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoNome.setText("Nome Produto:");

        textoCodigo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoCodigo.setText("Código Produto:");

        campoCodigo.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout painelAdicionarModificarProdutosLayout = new javax.swing.GroupLayout(painelAdicionarModificarProdutos);
        painelAdicionarModificarProdutos.setLayout(painelAdicionarModificarProdutosLayout);
        painelAdicionarModificarProdutosLayout.setHorizontalGroup(
            painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarModificarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelAdicionarModificarProdutosLayout.createSequentialGroup()
                        .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelAdicionarModificarProdutosLayout.createSequentialGroup()
                                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(campoValor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioInd, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(radioPrep))
                            .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textoErroIngrediente)
                    .addGroup(painelAdicionarModificarProdutosLayout.createSequentialGroup()
                        .addComponent(painelProdutoIndustrializado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelProdutoPreparado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelAdicionarModificarProdutosLayout.setVerticalGroup(
            painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarModificarProdutosLayout.createSequentialGroup()
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCodigo)
                    .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoValor)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioInd)
                    .addComponent(radioPrep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoErroIngrediente)
                .addGap(16, 16, 16)
                .addGroup(painelAdicionarModificarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelProdutoIndustrializado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelProdutoPreparado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        painelAdicionarModificarProdutosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {painelProdutoIndustrializado, painelProdutoPreparado});

        painelProcurarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Procurar Produto Existente"));

        textoCliqueParaEditar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoCliqueParaEditar.setText("Clique no produto desejado na lista para editá-lo no painel ao lado:");

        textoProcurarProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoProcurarProduto.setText("Procurar Produto:");

        campoPesquisarProduto.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoPesquisarProduto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoPesquisarProdutoFocusGained(evt);
            }
        });
        campoPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisarProdutoActionPerformed(evt);
            }
        });

        botaoProcurarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoProcurarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/search-26.png"))); // NOI18N
        botaoProcurarProduto.setText("Procurar");
        botaoProcurarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProcurarProdutoActionPerformed(evt);
            }
        });

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Descrição", "Valor"
            }
        ));
        painelScrollTabela.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(35);
        }

        javax.swing.GroupLayout painelProcurarProdutosLayout = new javax.swing.GroupLayout(painelProcurarProdutos);
        painelProcurarProdutos.setLayout(painelProcurarProdutosLayout);
        painelProcurarProdutosLayout.setHorizontalGroup(
            painelProcurarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProcurarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProcurarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelProcurarProdutosLayout.createSequentialGroup()
                        .addGroup(painelProcurarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoCliqueParaEditar)
                            .addGroup(painelProcurarProdutosLayout.createSequentialGroup()
                                .addComponent(textoProcurarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(campoPesquisarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoProcurarProduto)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addComponent(painelScrollTabela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelProcurarProdutosLayout.setVerticalGroup(
            painelProcurarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelProcurarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProcurarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoProcurarProduto)
                    .addComponent(campoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCliqueParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelScrollTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        botaoCancelarCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaoCancelarCadastro.setText("Cancelar Cadastro");
        botaoCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarCadastroActionPerformed(evt);
            }
        });

        botaoCadastrarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/ok-32.png"))); // NOI18N
        botaoCadastrarProduto.setText("Cadastrar Produto");
        botaoCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProdutoActionPerformed(evt);
            }
        });

        botaoLimparCampos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoLimparCampos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/erase-32.png"))); // NOI18N
        botaoLimparCampos.setText("Limpar Campos");
        botaoLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparCamposActionPerformed(evt);
            }
        });

        botaoAtualizarProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoAtualizarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/refresh-32.png"))); // NOI18N
        botaoAtualizarProduto.setText("Atualizar Produto");
        botaoAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarProdutoActionPerformed(evt);
            }
        });

        botaoExcluirProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/delete-32.png"))); // NOI18N
        botaoExcluirProduto.setText("Excluir Produto");
        botaoExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoExcluirProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoAtualizarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCancelarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoCadastrarProduto)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarCadastro)
                    .addComponent(botaoCadastrarProduto)
                    .addComponent(botaoLimparCampos)
                    .addComponent(botaoAtualizarProduto)
                    .addComponent(botaoExcluirProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(painelAdicionarModificarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelProcurarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelAdicionarModificarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelProcurarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoNomeFocusGained
        campoNome.selectAll();
    }//GEN-LAST:event_campoNomeFocusGained

    private void campoValorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoValorFocusGained
        campoValor.selectAll();
    }//GEN-LAST:event_campoValorFocusGained

    private void campoBarrasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoBarrasFocusGained
        campoBarras.selectAll();
    }//GEN-LAST:event_campoBarrasFocusGained

    private void campoPesquisarProdutoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoPesquisarProdutoFocusGained
        campoPesquisarProduto.selectAll();
    }//GEN-LAST:event_campoPesquisarProdutoFocusGained

    private void botaoAdicionarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarIngredienteActionPerformed
        adicionaIngrediente();
    }//GEN-LAST:event_botaoAdicionarIngredienteActionPerformed

    private void botaoCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProdutoActionPerformed
        if (valida()) {
            cadastrarProduto();
        }
    }//GEN-LAST:event_botaoCadastrarProdutoActionPerformed

    private void botaoLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparCamposActionPerformed
        limpaCampos();
        habilitaBotoesParaSalvar();
    }//GEN-LAST:event_botaoLimparCamposActionPerformed

    private void botaoExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirProdutoActionPerformed
        if (valida()) {
            excluirProduto();
            habilitaBotoesParaSalvar();
        }
    }//GEN-LAST:event_botaoExcluirProdutoActionPerformed

    private void botaoAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarProdutoActionPerformed
        if (valida()) {
            atualizarProduto();
            habilitaBotoesParaSalvar();
        }
    }//GEN-LAST:event_botaoAtualizarProdutoActionPerformed

    private void botaoCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarCadastroActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarCadastroActionPerformed

    private void radioIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIndActionPerformed
        habilitaInd(true);
        habilitaPrep(false);
        limpaPrep();
    }//GEN-LAST:event_radioIndActionPerformed

    private void radioPrepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPrepActionPerformed
        habilitaPrep(true);
        habilitaInd(false);
        limpaInd();
    }//GEN-LAST:event_radioPrepActionPerformed

    private void botaoProcurarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProcurarProdutoActionPerformed
        pesquisaProdutos();
    }//GEN-LAST:event_botaoProcurarProdutoActionPerformed

    private void campoPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisarProdutoActionPerformed
        pesquisaProdutos();
    }//GEN-LAST:event_campoPesquisarProdutoActionPerformed

    private void botaoRemoverIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverIngredienteActionPerformed
        excluirIngrediente();
    }//GEN-LAST:event_botaoRemoverIngredienteActionPerformed

    private void adicionaIngrediente() {
        CustomComboBoxInt ob = (CustomComboBoxInt) caixaSelecaoIng.getSelectedItem();

        for (int i = 0; i < tabelaIngredientes.getRowCount(); i++) {
            if (ob.getNome().equals(tabelaIngredientes.getValueAt(i, 0))) {
                return;
            }
        }
        Ingrediente ingrediente = new Ingrediente();
        ingrediente.setDescIng(ob.getNome());
        ingrediente.setIdIng(ob.getId());
        ingredientes.add(ingrediente);
        atualizaTableModelIngredientes();
    }

    public void atualizaTableModelIngredientes() {
        if (!ingredientes.isEmpty()) {
            tableModelIngredientes = new ProdutoIngredientesTableModel(ingredientes);
            tabelaIngredientes.setModel(tableModelIngredientes);
        }
    }

    public void atualizaTableModelProdutos(List<Produto> produtos) {
        if (produtos != null && produtos.isEmpty()) {
            Produto produto = new Produto();
            produto.setDescProd("Nenhum Registro Encontrado");
            produtos.add(produto);
        }
        tableModelProdutos = new ProdutoTableModel(produtos);
        tabelaProdutos.setModel(tableModelProdutos);
        tabelaProdutos.getSelectionModel().addListSelectionListener(this);
        tabelaProdutos.getColumnModel().getColumn(0).setMaxWidth(35);
        tabelaProdutos.getColumnModel().getColumn(2).setMaxWidth(75);
    }

    public void atualizarProduto() {
        pDao.abreConnection();
        Produto produto = formToProduto();
        deletarReceitas(produto.getIdProd());
        cadastrarReceitas(produto.getIdProd());
        pDao.atualizaProduto(produto);
        pDao.fechaConnection();
        JOptionPane.showMessageDialog(this, "Produto Atualizado Com Sucesso", "Cadastro de Produtos", JOptionPane.INFORMATION_MESSAGE);
        limpaCampos();
        inicializaTableModel();
    }

    private void cadastrarProduto() {
        pDao.abreConnection();
        Produto produto = formToProduto();
        if (pDao.validaNome(produto.getDescProd())) {
            JOptionPane.showMessageDialog(this, "Um produto com este nome já foi cadastrado!", "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
            return;
        } else if (pDao.validaCodigo(produto.getNumProd())) {
            JOptionPane.showMessageDialog(this, "Um produto com este código já foi cadastrado!", "Cadastro de Produtos", JOptionPane.WARNING_MESSAGE);
            return;
        }
        cadastrarReceitas(pDao.adicionaProduto(produto));
        pDao.fechaConnection();
        JOptionPane.showMessageDialog(this, "Produto Cadastrado Com Sucesso", "Cadastro de Produtos", JOptionPane.INFORMATION_MESSAGE);
        limpaCampos();
        ingredientes = new ArrayList<>();
        tableModelIngredientes = new ProdutoIngredientesTableModel(ingredientes);
        tabelaIngredientes.setModel(tableModelIngredientes);
        inicializaTableModel();
    }

    private void cadastrarReceitas(int idProd) {
        rDao.abreConnection();
        Receita receita = new Receita();
        receita.setIdProd(idProd);
        if (ingredientes != null && !ingredientes.isEmpty()) {
            for (int i = 0; i < ingredientes.size(); i++) {
                receita.setIdIng(ingredientes.get(i).getIdIng());
                rDao.adicionaReceita(receita);
            }
        }
        rDao.fechaConnection();
    }

    private void deletarReceitas(int idProd) {
        rDao.abreConnection();
        rDao.deletaIngredientesDoProduto(idProd);
        rDao.fechaConnection();
    }

    private void desabilitaBotoesParaSalvar() {
        habilitaOuDesabilitaBotoesEdicao(false);
    }

    private CustomComboBoxInt[] getIngs() {
        iDao.abreConnection();
        List<Ingrediente> listaResIng = iDao.getLista();
        iDao.fechaConnection();
        CustomComboBoxInt[] oItems = new CustomComboBoxInt[listaResIng.size()];
        for (int i = 0; i < listaResIng.size(); i++) {
            oItems[i] = new CustomComboBoxInt(listaResIng.get(i).getDescIng(), listaResIng.get(i).getIdIng());
        }
        return oItems;
    }

    private void excluirIngrediente() {
        if(tabelaIngredientes.getRowCount() != -1){
            ingredientes.remove(tabelaIngredientes.getSelectedRow());
            atualizaTableModelIngredientes();
        }
    }

    public void excluirProduto() {
        pDao.abreConnection();
        Produto produto = formToProduto();
        deletarReceitas(produto.getIdProd());
        pDao.deletaProduto(produto);
        JOptionPane.showMessageDialog(this, "Produto Removido Com Sucesso", "Cadastro de Produtos", JOptionPane.INFORMATION_MESSAGE);
        limpaCampos();
        inicializaTableModel();
    }

    private Produto formToProduto() {
        Produto produto = new Produto();
        if (id != null) {
            produto.setIdProd(id);
        }
        produto.setNumProd(Integer.valueOf(campoCodigo.getText()));
        produto.setDescProd(campoNome.getText());
        produto.setValorProd(Double.valueOf(campoValor.getText()));
        if (radioInd.isSelected()) {
            produto.setEIndustrializado((byte) 1);
            if ("".equals(campoBarras.getText())) {
                produto.setCodBarras(null);
            } else {
                produto.setCodBarras(campoBarras.getText());
            }
        } else {
            produto.setCodBarras(null);
            produto.setEIndustrializado((byte) 0);
            produto.setIngredientes(ingredientes);
        }
        return produto;
    }

    private void habilitaBotoesParaSalvar() {
        habilitaOuDesabilitaBotoesEdicao(true);
    }

    public void habilitaInd(boolean valida) {
        campoBarras.setText("");
        campoBarras.setEnabled(valida);
    }

    private void habilitaOuDesabilitaBotoesEdicao(boolean enabled) {
        botaoCadastrarProduto.setEnabled(enabled);
        botaoAtualizarProduto.setEnabled(!enabled);
        botaoExcluirProduto.setEnabled(!enabled);
    }

    public void habilitaPrep(boolean valida) {
        if (caixaSelecaoIng.getItemCount() > 0) {
            caixaSelecaoIng.setSelectedIndex(0);
            caixaSelecaoIng.setEnabled(valida);
            botaoAdicionarIngrediente.setEnabled(valida);
            limpaIngredientes();
            tabelaIngredientes.setEnabled(valida);
        } else if (valida) {
            Integer resposta;
            resposta = JOptionPane.showConfirmDialog(this, "Antes de cadastrar um produto preparado, é necessário ter ao menos um ingrediente cadastrado. \nDeseja cadastrar um novo ingrediente agora?", "Cadastro de Produtos", JOptionPane.YES_NO_OPTION);
            if (resposta == 0) {
                this.dispose();
                new TelaCadastrarIngrediente(null, true).setVisible(true);
                new TelaCadastrarProduto(null, true).setVisible(true);
            }
        }
    }

    private void inicializaTableModel() {
        pDao.abreConnection();
        atualizaTableModelProdutos(pDao.getLista());
        pDao.fechaConnection();
        atualizaTableModelIngredientes();
    }

    public void limpaCampos() {
        id = null;
        campoCodigo.setText("");
        campoBarras.setText("");
        campoNome.setText("");
        campoValor.setText("");
        buttonGroup1.clearSelection();
        caixaSelecaoIng.setSelectedIndex(-1);
        caixaSelecaoIng.setBorder(normal);
        campoBarras.setBorder(normal);
        campoNome.setBorder(normal);
        campoValor.setBorder(normal);
        textoErroIngrediente.setVisible(false);
        limpaInd();
        limpaPrep();
        limpaIngredientes();
        habilitaInd(false);
        habilitaPrep(false);
    }

    public void limpaInd() {
        radioInd.setBorderPainted(false);
        campoBarras.setBorder(normal);
    }

    public void limpaIngredientes() {

        ingredientes = new ArrayList<>();
        tableModelIngredientes = new ProdutoIngredientesTableModel(ingredientes);
        tabelaIngredientes.setModel(tableModelIngredientes);
    }

    public void limpaPrep() {
        radioPrep.setBorderPainted(false);

    }

    public void pesquisaProdutos() {
        pDao.abreConnection();
        String pesquisa = campoPesquisarProduto.getText();
        atualizaTableModelProdutos(pDao.pesquisarProduto("%" + pesquisa + "%"));
        pDao.fechaConnection();
    }

    private void produtoToForm(Produto produto) {
        iDao.abreConnection();
        id = produto.getIdProd();
        campoCodigo.setText(String.valueOf(produto.getNumProd()));
        campoNome.setText(produto.getDescProd());
        campoValor.setText(String.valueOf(produto.getValorProd()));
        if (produto.getEIndustrializado() == (byte) 1) {
            radioInd.doClick();
            radioPrep.setSelected(false);
            campoBarras.setText(produto.getCodBarras());
        } else {
            radioPrep.doClick();
            radioInd.setSelected(false);
            ingredientes = iDao.pesquisarIngredientePorProduto(produto.getIdProd());
            if(ingredientes == null){
                ingredientes = new ArrayList<>();
            }
            tableModelIngredientes = new ProdutoIngredientesTableModel(ingredientes);
            iDao.fechaConnection();
            tabelaIngredientes.setModel(tableModelIngredientes);
        }
        desabilitaBotoesParaSalvar();
    }

    public boolean valida() {
        boolean valida = true;
        if (!"".equals(campoCodigo.getText()) && campoCodigo.getText().length() > 0) {
            campoCodigo.setBorder(normal);
        } else {
            campoCodigo.setBorder(vermelha);
            valida = false;
        }
        if (!"".equals(campoNome.getText()) && campoNome.getText().length() > 2) {
            campoNome.setBorder(normal);
        } else {
            campoNome.setBorder(vermelha);
            valida = false;
        }
        if (!"".equals(campoValor.getText()) && campoValor.getText().length() > 0) {
            campoValor.setBorder(normal);
        } else {
            campoValor.setBorder(vermelha);
            valida = false;
        }
        if (radioInd.isSelected() || radioPrep.isSelected()) {
            radioInd.setBorderPainted(false);
            radioPrep.setBorderPainted(false);
        } else {
            radioInd.setBorderPainted(true);
            radioPrep.setBorderPainted(true);
            radioPrep.setBorder(vermelha);
            radioInd.setBorder(vermelha);
            valida = false;
        }
        if (radioPrep.isSelected()) {
            if (tabelaIngredientes.getRowCount() > 0) {
                textoErroIngrediente.setVisible(false);
            } else {
                textoErroIngrediente.setVisible(true);
                valida = false;
            }
        }
        return valida;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarIngrediente;
    private javax.swing.JButton botaoAtualizarProduto;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoCancelarCadastro;
    private javax.swing.JButton botaoExcluirProduto;
    private javax.swing.JButton botaoLimparCampos;
    private javax.swing.JButton botaoProcurarProduto;
    private javax.swing.JButton botaoRemoverIngrediente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox caixaSelecaoIng;
    private javax.swing.JTextField campoBarras;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPesquisarProduto;
    private javax.swing.JTextField campoValor;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel painelAdicionarModificarProdutos;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelProcurarProdutos;
    private javax.swing.JPanel painelProdutoIndustrializado;
    private javax.swing.JPanel painelProdutoPreparado;
    private javax.swing.JScrollPane painelScrollTabela;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JRadioButton radioInd;
    private javax.swing.JRadioButton radioPrep;
    private javax.swing.JTable tabelaIngredientes;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JLabel textoAdicionarProduto;
    private javax.swing.JLabel textoBarras;
    private javax.swing.JLabel textoCliqueParaEditar;
    private javax.swing.JLabel textoCodigo;
    private javax.swing.JLabel textoErroIngrediente;
    private javax.swing.JLabel textoIconeNovoProduto;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoPreencherDados;
    private javax.swing.JLabel textoProcurarProduto;
    private javax.swing.JLabel textoTipo;
    private javax.swing.JLabel textoValor;
    // End of variables declaration//GEN-END:variables

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (tabelaProdutos.getSelectedRow() != -1) {
            Produto produto = tableModelProdutos.getProdutos().get(tabelaProdutos.getSelectedRow());
            if (produto.getIdProd() != 0) {
                produtoToForm(produto);
            }
        }
        if (tabelaIngredientes.getRowCount() != -1) {
            botaoRemoverIngrediente.setEnabled(true);
        }
    }
}
