/*
 * Copyright (C) 2014 BrunoRicardo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.au.gui;

import com.au.bean.Funcionario;
import com.au.dao.FuncionarioDao;
import com.au.util.HexSha;
import com.au.util.LimitaDigitos;
import com.au.util.setarIcone;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.border.MatteBorder;
import javax.swing.plaf.FontUIResource;

/**
 *
 * @author tiago_000
 */
public class TelaLogin extends javax.swing.JFrame {
    private final Border vermelha = new MatteBorder(1, 1, 1, 1, Color.red);
    private final Border normal;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        normal = campoUsuario.getBorder();
        textoErroUsuario.setVisible(false);
        textoErroSenha.setVisible(false);
        setaFonteAvisos();
        campoSenha.setDocument(new LimitaDigitos((64), ""));
        campoUsuario.setDocument(new LimitaDigitos((50), "[^0-9a-zA-Z\\-._]"));
        setarIcone i = new setarIcone(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        textoBemVindo = new javax.swing.JLabel();
        textoInsiraDados = new javax.swing.JLabel();
        painelInferior = new javax.swing.JPanel();
        textoUsuario = new javax.swing.JLabel();
        textoSenha = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        campoSenha = new javax.swing.JPasswordField();
        campoSenha.setActionCommand("Entrar no Sistema");
        textoErroUsuario = new javax.swing.JLabel();
        textoErroSenha = new javax.swing.JLabel();
        botaoEsqueciSenha = new javax.swing.JButton();
        botaoEntrarNoSistema = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Pastelão - Efetuar Login");
        setIconImages(null);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoBemVindo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        textoBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoBemVindo.setText("Bem-Vindo");

        textoInsiraDados.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        textoInsiraDados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoInsiraDados.setText("Insira os dados abaixo para efetuar o login no sistema:");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoInsiraDados, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoBemVindo)
                .addGap(18, 18, 18)
                .addComponent(textoInsiraDados)
                .addContainerGap())
        );

        painelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoUsuario.setText("Usuário:");

        textoSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoSenha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textoSenha.setText("Senha:");

        campoUsuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        campoUsuario.setNextFocusableComponent(campoSenha);
        campoUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoUsuarioFocusLost(evt);
            }
        });
        campoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUsuarioActionPerformed(evt);
            }
        });

        campoSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        campoSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                campoSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoSenhaFocusLost(evt);
            }
        });
        campoSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoSenhaActionPerformed(evt);
            }
        });

        textoErroUsuario.setForeground(new java.awt.Color(255, 0, 0));
        textoErroUsuario.setText("Informe o usuário");

        textoErroSenha.setForeground(new java.awt.Color(255, 0, 0));
        textoErroSenha.setText("Informe a senha");

        javax.swing.GroupLayout painelInferiorLayout = new javax.swing.GroupLayout(painelInferior);
        painelInferior.setLayout(painelInferiorLayout);
        painelInferiorLayout.setHorizontalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSenha)
                    .addComponent(textoUsuario))
                .addGap(18, 18, 18)
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                    .addComponent(campoSenha)
                    .addGroup(painelInferiorLayout.createSequentialGroup()
                        .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoErroSenha)
                            .addComponent(textoErroUsuario))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelInferiorLayout.setVerticalGroup(
            painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoUsuario)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoErroUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoErroSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoEsqueciSenha.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoEsqueciSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/help-32.png"))); // NOI18N
        botaoEsqueciSenha.setText("Esqueci a minha senha");
        botaoEsqueciSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEsqueciSenhaActionPerformed(evt);
            }
        });

        botaoEntrarNoSistema.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        botaoEntrarNoSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/login-32.png"))); // NOI18N
        botaoEntrarNoSistema.setText("Entrar no Sistema");
        botaoEntrarNoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntrarNoSistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelInferior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoEsqueciSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoEntrarNoSistema)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {botaoEntrarNoSistema, botaoEsqueciSenha});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelInferior, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoEntrarNoSistema)
                    .addComponent(botaoEsqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campoUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusGained
        campoUsuario.selectAll();
    }//GEN-LAST:event_campoUsuarioFocusGained

    private void campoSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusGained
        campoSenha.selectAll();
    }//GEN-LAST:event_campoSenhaFocusGained

    private void botaoEntrarNoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntrarNoSistemaActionPerformed
        logar();
    }//GEN-LAST:event_botaoEntrarNoSistemaActionPerformed

    private void botaoEsqueciSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEsqueciSenhaActionPerformed
        trocarSenha();
    }//GEN-LAST:event_botaoEsqueciSenhaActionPerformed

    private void campoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUsuarioActionPerformed
        campoSenha.requestFocus();
    }//GEN-LAST:event_campoUsuarioActionPerformed

    private void campoSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoSenhaActionPerformed
        logar();
    }//GEN-LAST:event_campoSenhaActionPerformed

    private void campoUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoUsuarioFocusLost
        valida(campoUsuario, 3, textoErroUsuario);
    }//GEN-LAST:event_campoUsuarioFocusLost

    private void campoSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoSenhaFocusLost
        valida(campoSenha, 3, textoErroSenha);
    }//GEN-LAST:event_campoSenhaFocusLost
    
    public void valida(JTextField campo, Integer tamanho, JLabel texto) {

        if (campo != null && !"".equals(campo.getText()) && campo.getText().length() > tamanho) {
            campo.setBorder(normal);
            texto.setVisible(false);
        } else {
            campo.setBorder(vermelha);
            texto.setVisible(true);
        }
    }
    
    public void limpaCampos() {
        campoSenha.setText("");
        campoUsuario.setText("");
    }

    private void logar() {
        Funcionario funcionario;
        Funcionario login = new Funcionario();
        try {
            login.setUserFunc(campoUsuario.getText());
            HexSha hexSha = new HexSha(String.valueOf(campoSenha.getPassword()));
            login.setPassFunc(hexSha.ConvertSha());
            FuncionarioDao fDao = new FuncionarioDao();
            fDao.abreConnection();
            funcionario = fDao.buscarLogin(login.getUserFunc(), login.getPassFunc());
            fDao.fechaConnection();
            if (funcionario == null) {
                JOptionPane.showMessageDialog(this, "Senha ou Usuario Invalidos", "Efetuar Login", JOptionPane.WARNING_MESSAGE);
            } else if (funcionario.getUserFunc().equals(login.getUserFunc()) && funcionario.getPassFunc().equals(login.getPassFunc()) && funcionario.getEstaAtivo() == 1) {
                new com.au.gui.TelaVenda(funcionario).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Esta conta foi desativada pelo Administrador", "Efetuar Login", JOptionPane.WARNING_MESSAGE);
            }
        } catch (ExceptionInInitializerError ex) {
            Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Erro ao tentar conectar com o banco de dados. \n Verifique se o Banco de Dados está funcionado e tente novamente.", "Efetuar Login", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void setaFonteAvisos() {
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 15)));
        UIManager.put("OptionPane.buttonFont", new FontUIResource(new Font("Tahoma", Font.PLAIN, 16)));
        //UIManager.put("Button.font", /* font of your liking */);
        //UIManager.put("ToggleButton.font", /* font of your liking */);
        //UIManager.put("RadioButton.font", /* font of your liking */);
        //UIManager.put("CheckBox.font", /* font of your liking */);
        //UIManager.put("ColorChooser.font", /* font of your liking */);
        UIManager.put("ComboBox.font", new FontUIResource(new Font("Tahoma", Font.PLAIN, 15)));
        //UIManager.put("Label.font", /* font of your liking */);
        //UIManager.put("List.font", /* font of your liking */);
        UIManager.put("MenuBar.font", new FontUIResource(new Font("Tahoma", Font.PLAIN, 18)));
        UIManager.put("MenuItem.font", new FontUIResource(new Font("Tahoma", Font.PLAIN, 16)));
        //UIManager.put("RadioButtonMenuItem.font", /* font of your liking */);
        //UIManager.put("CheckBoxMenuItem.font", /* font of your liking */);
        //UIManager.put("Menu.font", /* font of your liking */);
        //UIManager.put("PopupMenu.font", /* font of your liking */);
        //UIManager.put("OptionPane.font", /* font of your liking */);
        //UIManager.put("Panel.font", /* font of your liking */);
        //UIManager.put("ProgressBar.font", /* font of your liking */);
        //UIManager.put("ScrollPane.font", /* font of your liking */);
        //UIManager.put("Viewport.font", /* font of your liking */);
        //UIManager.put("TabbedPane.font", /* font of your liking */);
        UIManager.put("Table.font", new FontUIResource(new Font("Tahoma", Font.PLAIN, 15)));
        UIManager.put("TableHeader.font", new FontUIResource(new Font("Tahoma", Font.BOLD, 15)));
        //UIManager.put("TextField.font", /* font of your liking */);
        //UIManager.put("PasswordField.font", /* font of your liking */);
        //UIManager.put("TextArea.font", /* font of your liking */);
        //UIManager.put("TextPane.font", /* font of your liking */);
        //UIManager.put("EditorPane.font", /* font of your liking */);
        UIManager.put("TitledBorder.font", new FontUIResource(new Font("Tahoma", Font.BOLD, 15)));
        //UIManager.put("ToolBar.font", /* font of your liking */);
        //UIManager.put("ToolTip.font", /* font of your liking */); 
    }

    private void trocarSenha() {
        new TelaCriarNovaSenha(this, true).setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEntrarNoSistema;
    private javax.swing.JButton botaoEsqueciSenha;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JPanel painelInferior;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JLabel textoBemVindo;
    private javax.swing.JLabel textoErroSenha;
    private javax.swing.JLabel textoErroUsuario;
    private javax.swing.JLabel textoInsiraDados;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoUsuario;
    // End of variables declaration//GEN-END:variables
}
