/*
 * The MIT License
 *
 * Copyright 2014 tiago_000.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.au.gui;

import com.au.util.LimitaDigitos;
import com.au.gui.listener.ProdutoActionListener;
import com.au.modelo.Fornecedor;
import com.au.modelo.Ingrediente;
import com.au.util.CustomComboBoxInt;
import com.au.util.DAO;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author tiago_000
 */
public class TelaCadastrarProduto extends javax.swing.JFrame {

    private ProdutoActionListener listener;
    
    /**
     * Creates new form TelaCadastrarUsuario
     */
    public TelaCadastrarProduto() {
        initComponents();
        campoId.setDocument(new LimitaDigitos((250), "[^0-9]"));
        campoNome.setDocument(new LimitaDigitos((250), "[^a-z|^A-Z|^0-9|^ |^~]"));
        campoValor.setDocument(new LimitaDigitos((7), "[^0-9|^.]"));
        campoQtd.setDocument(new LimitaDigitos((15), "[^0-9]"));
        campoBarras.setDocument(new LimitaDigitos((150), "[^0-9]"));
        caixaSelecaoForn.setSelectedIndex(-1);
        tabelaProdutos.getColumnModel().getColumn(0).setPreferredWidth(50);
        tabelaProdutos.getColumnModel().getColumn(1).setPreferredWidth(1000);
        tabelaProdutos.getColumnModel().getColumn(2).setPreferredWidth(70);
        
        listener = new ProdutoActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        painelSuperior = new javax.swing.JPanel();
        textoAdicionarProduto = new javax.swing.JLabel();
        textoIconeNovoProduto = new javax.swing.JLabel();
        textoPreencherDados = new javax.swing.JLabel();
        painelEsquerdo = new javax.swing.JPanel();
        painelDadosProduto = new javax.swing.JPanel();
        textoId = new javax.swing.JLabel();
        textoFornecedor = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        textoNome = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        campoNome = new javax.swing.JTextField();
        textoValor = new javax.swing.JLabel();
        caixaSelecaoForn = new javax.swing.JComboBox(getForns());
        textoTipo = new javax.swing.JLabel();
        radioInd = new javax.swing.JRadioButton();
        radioPrep = new javax.swing.JRadioButton();
        botaoAdicionarFornecedor = new javax.swing.JButton();
        painelProdutoIndustrializado = new javax.swing.JPanel();
        textoQtd = new javax.swing.JLabel();
        textoBarras = new javax.swing.JLabel();
        campoQtd = new javax.swing.JTextField();
        campoBarras = new javax.swing.JTextField();
        painelProdutoPreparado = new javax.swing.JPanel();
        caixaSelecaoIng = new javax.swing.JComboBox(getIngs());
        botaoNovoIngrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaIngredientes = new javax.swing.JTable();
        botaoAdicionarIngrediente = new javax.swing.JButton();
        painelEditarProdutos = new javax.swing.JPanel();
        textoCliqueParaEditar = new javax.swing.JLabel();
        textoProcurarProduto = new javax.swing.JLabel();
        textoPesquisarProduto = new javax.swing.JTextField();
        botaoProcurarProduto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        painelBotoesAdicionar = new javax.swing.JPanel();
        botaoCancelarCadastro = new javax.swing.JButton();
        botaoCadastrarProduto = new javax.swing.JButton();
        painelBotoesModificar = new javax.swing.JPanel();
        botaoExcluirProduto = new javax.swing.JButton();
        botaoAtualizarProduto = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Adicionar/Modificar Produto - Sistema Pastelão");

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoAdicionarProduto.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoAdicionarProduto.setText("Adicionar Novo Produto");

        textoIconeNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/beer_glass-64.png"))); // NOI18N

        textoPreencherDados.setText("Preencha os dados abaixo para adicionar um novo produto.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIconeNovoProduto)
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoAdicionarProduto)
                    .addComponent(textoPreencherDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoIconeNovoProduto)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(textoAdicionarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPreencherDados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelEsquerdo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Adicionar/Modificar Produto"));

        painelDadosProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Produto"));

        textoId.setText("Id Produto:");

        textoFornecedor.setText("Fornecedor:");

        campoId.setEnabled(false);

        textoNome.setText("Nome Produto:");

        textoValor.setText("Valor Produto:");

        textoTipo.setText("Tipo Produto:");

        buttonGroup1.add(radioInd);
        radioInd.setText("Industrializado");

        buttonGroup1.add(radioPrep);
        radioPrep.setText("Preparado");

        botaoAdicionarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/plus-26.png"))); // NOI18N
        botaoAdicionarFornecedor.setText("Novo Fornecedor");

        javax.swing.GroupLayout painelDadosProdutoLayout = new javax.swing.GroupLayout(painelDadosProduto);
        painelDadosProduto.setLayout(painelDadosProdutoLayout);
        painelDadosProdutoLayout.setHorizontalGroup(
            painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(textoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                        .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(campoValor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioInd, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(radioPrep))
                    .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                        .addComponent(caixaSelecaoForn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botaoAdicionarFornecedor))
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        painelDadosProdutoLayout.setVerticalGroup(
            painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDadosProdutoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoId)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNome)
                    .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoValor)
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioInd)
                    .addComponent(radioPrep))
                .addGap(18, 18, 18)
                .addGroup(painelDadosProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFornecedor)
                    .addComponent(caixaSelecaoForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarFornecedor))
                .addContainerGap())
        );

        painelProdutoIndustrializado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Industrializado")));

        textoQtd.setText("Quantidade");

        textoBarras.setText("Código Barras");

        javax.swing.GroupLayout painelProdutoIndustrializadoLayout = new javax.swing.GroupLayout(painelProdutoIndustrializado);
        painelProdutoIndustrializado.setLayout(painelProdutoIndustrializadoLayout);
        painelProdutoIndustrializadoLayout.setHorizontalGroup(
            painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoIndustrializadoLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoBarras)
                    .addComponent(textoQtd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBarras)
                    .addGroup(painelProdutoIndustrializadoLayout.createSequentialGroup()
                        .addComponent(campoQtd)
                        .addGap(84, 84, 84)))
                .addContainerGap())
        );
        painelProdutoIndustrializadoLayout.setVerticalGroup(
            painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoIndustrializadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoQtd)
                    .addComponent(campoQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelProdutoIndustrializadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoBarras)
                    .addComponent(campoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelProdutoPreparado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Preparado"));

        botaoNovoIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/plus-32.png"))); // NOI18N
        botaoNovoIngrediente.setText("Novo Ingrediente");

        tabelaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descrição"
            }
        ));
        jScrollPane2.setViewportView(tabelaIngredientes);

        botaoAdicionarIngrediente.setText("Adiciona Ingrediente");

        javax.swing.GroupLayout painelProdutoPreparadoLayout = new javax.swing.GroupLayout(painelProdutoPreparado);
        painelProdutoPreparado.setLayout(painelProdutoPreparadoLayout);
        painelProdutoPreparadoLayout.setHorizontalGroup(
            painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoPreparadoLayout.createSequentialGroup()
                .addComponent(botaoNovoIngrediente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(painelProdutoPreparadoLayout.createSequentialGroup()
                .addComponent(caixaSelecaoIng, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoAdicionarIngrediente))
        );
        painelProdutoPreparadoLayout.setVerticalGroup(
            painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelProdutoPreparadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelProdutoPreparadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caixaSelecaoIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAdicionarIngrediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNovoIngrediente))
        );

        javax.swing.GroupLayout painelEsquerdoLayout = new javax.swing.GroupLayout(painelEsquerdo);
        painelEsquerdo.setLayout(painelEsquerdoLayout);
        painelEsquerdoLayout.setHorizontalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDadosProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelEsquerdoLayout.createSequentialGroup()
                        .addComponent(painelProdutoIndustrializado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelProdutoPreparado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        painelEsquerdoLayout.setVerticalGroup(
            painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEsquerdoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelDadosProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEsquerdoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelProdutoPreparado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelProdutoIndustrializado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelEditarProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Editar Produto Existente"));

        textoCliqueParaEditar.setText("Clique no produto desejado na lista para editá-lo no painel ao lado:");

        textoProcurarProduto.setText("Procurar Produto:");

        botaoProcurarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/search-26.png"))); // NOI18N
        botaoProcurarProduto.setText("Procurar");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabelaProdutos);

        javax.swing.GroupLayout painelEditarProdutosLayout = new javax.swing.GroupLayout(painelEditarProdutos);
        painelEditarProdutos.setLayout(painelEditarProdutosLayout);
        painelEditarProdutosLayout.setHorizontalGroup(
            painelEditarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEditarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEditarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelEditarProdutosLayout.createSequentialGroup()
                        .addComponent(textoCliqueParaEditar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelEditarProdutosLayout.createSequentialGroup()
                        .addComponent(textoProcurarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPesquisarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoProcurarProduto)))
                .addContainerGap())
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        painelEditarProdutosLayout.setVerticalGroup(
            painelEditarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelEditarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEditarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoProcurarProduto)
                    .addComponent(textoPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCliqueParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3))
        );

        botaoCancelarCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaoCancelarCadastro.setText("Cancelar Cadastro");

        botaoCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/ok-32.png"))); // NOI18N
        botaoCadastrarProduto.setText("Cadastrar Produto");

        javax.swing.GroupLayout painelBotoesAdicionarLayout = new javax.swing.GroupLayout(painelBotoesAdicionar);
        painelBotoesAdicionar.setLayout(painelBotoesAdicionarLayout);
        painelBotoesAdicionarLayout.setHorizontalGroup(
            painelBotoesAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoCancelarCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCadastrarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesAdicionarLayout.setVerticalGroup(
            painelBotoesAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesAdicionarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesAdicionarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarCadastro)
                    .addComponent(botaoCadastrarProduto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/delete-32.png"))); // NOI18N
        botaoExcluirProduto.setText("Excluir Produto");

        botaoAtualizarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/refresh-32.png"))); // NOI18N
        botaoAtualizarProduto.setText("Atualizar Produto");

        javax.swing.GroupLayout painelBotoesModificarLayout = new javax.swing.GroupLayout(painelBotoesModificar);
        painelBotoesModificar.setLayout(painelBotoesModificarLayout);
        painelBotoesModificarLayout.setHorizontalGroup(
            painelBotoesModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoExcluirProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoAtualizarProduto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelBotoesModificarLayout.setVerticalGroup(
            painelBotoesModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExcluirProduto)
                    .addComponent(botaoAtualizarProduto))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        menuArquivo.setText("Arquivo");
        barraMenu.add(menuArquivo);

        menuEditar.setText("Editar");
        barraMenu.add(menuEditar);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEsquerdo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelEditarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(painelBotoesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelBotoesAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelEditarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelEsquerdo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelBotoesAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBotoesModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBotaoAdicionarFornecedor() {
        return botaoAdicionarFornecedor;
    }

    public void setBotaoAdicionarFornecedor(JButton botaoAdicionarFornecedor) {
        this.botaoAdicionarFornecedor = botaoAdicionarFornecedor;
    }

    public JButton getBotaoAdicionarIngrediente() {
        return botaoAdicionarIngrediente;
    }

    public void setBotaoAdicionarIngrediente(JButton botaoAdicionarIngrediente) {
        this.botaoAdicionarIngrediente = botaoAdicionarIngrediente;
    }

    public JButton getBotaoAtualizarProduto() {
        return botaoAtualizarProduto;
    }

    public void setBotaoAtualizarProduto(JButton botaoAtualizarProduto) {
        this.botaoAtualizarProduto = botaoAtualizarProduto;
    }

    public JButton getBotaoCadastrarProduto() {
        return botaoCadastrarProduto;
    }

    public void setBotaoCadastrarProduto(JButton botaoCadastrarProduto) {
        this.botaoCadastrarProduto = botaoCadastrarProduto;
    }

    public JButton getBotaoCancelarCadastro() {
        return botaoCancelarCadastro;
    }

    public void setBotaoCancelarCadastro(JButton botaoCancelarCadastro) {
        this.botaoCancelarCadastro = botaoCancelarCadastro;
    }

    public JButton getBotaoExcluirProduto() {
        return botaoExcluirProduto;
    }

    public void setBotaoExcluirProduto(JButton botaoExcluirProduto) {
        this.botaoExcluirProduto = botaoExcluirProduto;
    }

    public JButton getBotaoNovoIngrediente() {
        return botaoNovoIngrediente;
    }

    public void setBotaoNovoIngrediente(JButton botaoNovoIngrediente) {
        this.botaoNovoIngrediente = botaoNovoIngrediente;
    }

    public JButton getBotaoProcurarProduto() {
        return botaoProcurarProduto;
    }

    public void setBotaoProcurarProduto(JButton botaoProcurarProduto) {
        this.botaoProcurarProduto = botaoProcurarProduto;
    }

    public JComboBox getCaixaSelecaoForn() {
        return caixaSelecaoForn;
    }

    public void setCaixaSelecaoForn(JComboBox caixaSelecaoForn) {
        this.caixaSelecaoForn = caixaSelecaoForn;
    }

    public JComboBox getCaixaSelecaoIng() {
        return caixaSelecaoIng;
    }

    public void setCaixaSelecaoIng(JComboBox caixaSelecaoIng) {
        this.caixaSelecaoIng = caixaSelecaoIng;
    }

    public JTextField getCampoBarras() {
        return campoBarras;
    }

    public void setCampoBarras(JTextField campoBarras) {
        this.campoBarras = campoBarras;
    }

    public JTextField getCampoId() {
        return campoId;
    }

    public void setCampoId(JTextField campoId) {
        this.campoId = campoId;
    }

    public JTextField getCampoNome() {
        return campoNome;
    }

    public void setCampoNome(JTextField campoNome) {
        this.campoNome = campoNome;
    }

    public JTextField getCampoQtd() {
        return campoQtd;
    }

    public void setCampoQtd(JTextField campoQtd) {
        this.campoQtd = campoQtd;
    }

    public JTextField getCampoValor() {
        return campoValor;
    }

    public void setCampoValor(JTextField campoValor) {
        this.campoValor = campoValor;
    }

    public JRadioButton getRadioInd() {
        return radioInd;
    }

    public void setRadioInd(JRadioButton radioInd) {
        this.radioInd = radioInd;
    }

    public JRadioButton getRadioPrep() {
        return radioPrep;
    }

    public void setRadioPrep(JRadioButton radioPrep) {
        this.radioPrep = radioPrep;
    }

    public JTable getTabelaIngredientes() {
        return tabelaIngredientes;
    }

    public void setTabelaIngredientes(JTable tabelaIngredientes) {
        this.tabelaIngredientes = tabelaIngredientes;
    }

    public JTable getTabelaProdutos() {
        return tabelaProdutos;
    }

    public void setTabelaProdutos(JTable tabelaProdutos) {
        this.tabelaProdutos = tabelaProdutos;
    }

   
    
    private CustomComboBoxInt[] getForns() {
        List<Fornecedor>listaResForn = new DAO<>(Fornecedor.class).listaTodos();
        
        CustomComboBoxInt[] oItems = new CustomComboBoxInt[listaResForn.size()];
        
        for (int i = 0; i < listaResForn.size(); i++) {
            oItems[i] = new CustomComboBoxInt(listaResForn.get(i).getNomeForn(), listaResForn.get(i).getIdForn());
        }
        return oItems;
    }

    private CustomComboBoxInt[] getIngs() {
        List<Ingrediente>listaResIng = new DAO<>(Ingrediente.class).listaTodos();
        
        CustomComboBoxInt[] oItems = new CustomComboBoxInt[listaResIng.size()];
        for (int i = 0; i < listaResIng.size(); i++) {
            oItems[i] = new CustomComboBoxInt(listaResIng.get(i).getDescIng(), listaResIng.get(i).getIdIng());
        }
        return oItems;
    }
    
    public void limpaCampos(){
        campoId.setText("");
        campoBarras.setText("");
        campoNome.setText("");
        campoQtd.setText("");
        campoValor.setText("");
        radioInd.setSelected(false);
        radioPrep.setSelected(false);
        caixaSelecaoForn.setSelectedIndex(-1);
        caixaSelecaoIng.setSelectedIndex(-1);        
    }     
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrarProduto().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botaoAdicionarFornecedor;
    private javax.swing.JButton botaoAdicionarIngrediente;
    private javax.swing.JButton botaoAtualizarProduto;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JButton botaoCancelarCadastro;
    private javax.swing.JButton botaoExcluirProduto;
    private javax.swing.JButton botaoNovoIngrediente;
    private javax.swing.JButton botaoProcurarProduto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox caixaSelecaoForn;
    private javax.swing.JComboBox caixaSelecaoIng;
    private javax.swing.JTextField campoBarras;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoQtd;
    private javax.swing.JTextField campoValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JPanel painelBotoesAdicionar;
    private javax.swing.JPanel painelBotoesModificar;
    private javax.swing.JPanel painelDadosProduto;
    private javax.swing.JPanel painelEditarProdutos;
    private javax.swing.JPanel painelEsquerdo;
    private javax.swing.JPanel painelProdutoIndustrializado;
    private javax.swing.JPanel painelProdutoPreparado;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JRadioButton radioInd;
    private javax.swing.JRadioButton radioPrep;
    private javax.swing.JTable tabelaIngredientes;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JLabel textoAdicionarProduto;
    private javax.swing.JLabel textoBarras;
    private javax.swing.JLabel textoCliqueParaEditar;
    private javax.swing.JLabel textoFornecedor;
    private javax.swing.JLabel textoIconeNovoProduto;
    private javax.swing.JLabel textoId;
    private javax.swing.JLabel textoNome;
    private javax.swing.JTextField textoPesquisarProduto;
    private javax.swing.JLabel textoPreencherDados;
    private javax.swing.JLabel textoProcurarProduto;
    private javax.swing.JLabel textoQtd;
    private javax.swing.JLabel textoTipo;
    private javax.swing.JLabel textoValor;
    // End of variables declaration//GEN-END:variables
}
