/*
 * The MIT License
 *
 * Copyright 2014 tiago_000.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package com.au.gui;

import com.au.gui.listener.IngredienteActionListener;
import com.au.util.LimitaDigitos;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author tiago_000
 */
public class TelaVisualizarCaixa extends javax.swing.JDialog {

    private IngredienteActionListener listener;

    /**
     * Creates new form TelaCadastrarUsuario
     */
    public TelaVisualizarCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        campoId.setEditable(false);
        campoNome.setDocument(new LimitaDigitos((250), "[^a-zA-Z À-ÄÈ-ËÌ-ÏÒ-ÖÙ-Üà-äè-ëì-ïò-öù-ü]"));
        campoValor.setDocument(new LimitaDigitos((7), "[^0-9\\.]"));
        campoPesquisarIngrediente.setDocument(new LimitaDigitos((250), "[^a-zA-Z À-ÄÈ-ËÌ-ÏÒ-ÖÙ-Üà-äè-ëì-ïò-öù-ü0-9]"));
        .requestFocus();
        //listener = new IngredienteActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        painelSuperior = new javax.swing.JPanel();
        textoVisualizarCaixas = new javax.swing.JLabel();
        textoIconeVisualizarCaixas = new javax.swing.JLabel();
        textoPreencherDados = new javax.swing.JLabel();
        painelBuscarCaixa = new javax.swing.JPanel();
        botaoProcurarCaixa = new javax.swing.JButton();
        textoDataAberturaCaixa = new javax.swing.JLabel();
        textoCaixasAbertos = new javax.swing.JLabel();
        comboBoxCaixasAbertos = new javax.swing.JComboBox();
        dateChooserDataAberturaCaixa = new com.toedter.calendar.JDateChooser();
        separadorBuscaResultado = new javax.swing.JSeparator();
        textoCliqueParaEditar = new javax.swing.JLabel();
        painelScrollCaixasEncontrados = new javax.swing.JScrollPane();
        tabelaCaixasEncontrados = new javax.swing.JTable();
        painelDetalhesCaixa = new javax.swing.JPanel();
        painelInformacoesGerais = new javax.swing.JPanel();
        textoQuantidadePedidos = new javax.swing.JLabel();
        textoValorQuantidadePedidos = new javax.swing.JLabel();
        textoValorPagoComDinheiro = new javax.swing.JLabel();
        textoValorPagoComCredito = new javax.swing.JLabel();
        textoValorPagoComDebito = new javax.swing.JLabel();
        textoValorPagoComVale = new javax.swing.JLabel();
        textoPagoComVale = new javax.swing.JLabel();
        textoPagoComDebito = new javax.swing.JLabel();
        textoPagoComCredito = new javax.swing.JLabel();
        textoPagoComDinheiro = new javax.swing.JLabel();
        textoFundoCaixa = new javax.swing.JLabel();
        textoValorFundoCaixa = new javax.swing.JLabel();
        painelFaturamento = new javax.swing.JPanel();
        textoValorQuantidadePedidos1 = new javax.swing.JLabel();
        textoDinheiro = new javax.swing.JLabel();
        textoTotalFaturado = new javax.swing.JLabel();
        textoValorDinheiro = new javax.swing.JLabel();
        textoValorCredito = new javax.swing.JLabel();
        textoPagoComCredito1 = new javax.swing.JLabel();
        textoDebito = new javax.swing.JLabel();
        textoValorDebito = new javax.swing.JLabel();
        textoValorVale = new javax.swing.JLabel();
        textoVale = new javax.swing.JLabel();
        painelBalancoCaixa = new javax.swing.JPanel();
        painelRetiradas = new javax.swing.JPanel();
        painelDescontos = new javax.swing.JPanel();
        painelCancelamentos = new javax.swing.JPanel();
        painelBotoes = new javax.swing.JPanel();
        botaoCancelarIngrediente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoVisualizarCaixas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoVisualizarCaixas.setText("Visualizar Caixas");

        textoIconeVisualizarCaixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/bill-64.png"))); // NOI18N

        textoPreencherDados.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        textoPreencherDados.setText("Preencha os dados abaixo para visualizar os caixas existentes.");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoIconeVisualizarCaixas)
                .addGap(18, 18, 18)
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoVisualizarCaixas)
                    .addComponent(textoPreencherDados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoIconeVisualizarCaixas)
                    .addGroup(painelSuperiorLayout.createSequentialGroup()
                        .addComponent(textoVisualizarCaixas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textoPreencherDados)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBuscarCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Caixa"));
        painelBuscarCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        botaoProcurarCaixa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoProcurarCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/search-26.png"))); // NOI18N
        botaoProcurarCaixa.setText("Procurar");

        textoDataAberturaCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoDataAberturaCaixa.setText("Data de Abertura do Caixa:");

        textoCaixasAbertos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoCaixasAbertos.setText("Incluir Caixas Abertos?");

        comboBoxCaixasAbertos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sim", "Não" }));

        dateChooserDataAberturaCaixa.setDateFormatString("dd-MM-yyyy");
        dateChooserDataAberturaCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        textoCliqueParaEditar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoCliqueParaEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCliqueParaEditar.setText("Clique no caixa desejado na lista para editá-lo no painel ao lado:");

        tabelaCaixasEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Funcionário Responsável", "Data de Abertura", "Hora de Abertura", "Hora de Fechamento"
            }
        ));
        painelScrollCaixasEncontrados.setViewportView(tabelaCaixasEncontrados);

        javax.swing.GroupLayout painelBuscarCaixaLayout = new javax.swing.GroupLayout(painelBuscarCaixa);
        painelBuscarCaixa.setLayout(painelBuscarCaixaLayout);
        painelBuscarCaixaLayout.setHorizontalGroup(
            painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscarCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(separadorBuscaResultado)
                    .addComponent(textoCliqueParaEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelBuscarCaixaLayout.createSequentialGroup()
                        .addGroup(painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelBuscarCaixaLayout.createSequentialGroup()
                                .addComponent(textoDataAberturaCaixa)
                                .addGap(18, 18, 18)
                                .addComponent(dateChooserDataAberturaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelBuscarCaixaLayout.createSequentialGroup()
                                .addComponent(textoCaixasAbertos)
                                .addGap(18, 18, 18)
                                .addComponent(comboBoxCaixasAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botaoProcurarCaixa)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelScrollCaixasEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        painelBuscarCaixaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textoCaixasAbertos, textoDataAberturaCaixa});

        painelBuscarCaixaLayout.setVerticalGroup(
            painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBuscarCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botaoProcurarCaixa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelBuscarCaixaLayout.createSequentialGroup()
                        .addGroup(painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoDataAberturaCaixa)
                            .addComponent(dateChooserDataAberturaCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBuscarCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCaixasAbertos)
                            .addComponent(comboBoxCaixasAbertos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(separadorBuscaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoCliqueParaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelScrollCaixasEncontrados, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelDetalhesCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Detalhes do Caixa"));

        painelInformacoesGerais.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações Gerais"));

        textoQuantidadePedidos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoQuantidadePedidos.setText("Quantidade de Pedidos:");

        textoValorQuantidadePedidos.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorQuantidadePedidos.setText("0");

        textoValorPagoComDinheiro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorPagoComDinheiro.setText("0");

        textoValorPagoComCredito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorPagoComCredito.setText("0");

        textoValorPagoComDebito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorPagoComDebito.setText("0");

        textoValorPagoComVale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorPagoComVale.setText("0");

        textoPagoComVale.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoPagoComVale.setText("Pagos com Vale:");

        textoPagoComDebito.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoPagoComDebito.setText("Pagos com Débito:");

        textoPagoComCredito.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoPagoComCredito.setText("Pagos com Crédito:");

        textoPagoComDinheiro.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoPagoComDinheiro.setText("Pagos com Dinheiro:");

        textoFundoCaixa.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoFundoCaixa.setText("Fundo de Caixa:");

        textoValorFundoCaixa.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorFundoCaixa.setText("R$ 0,00");

        javax.swing.GroupLayout painelInformacoesGeraisLayout = new javax.swing.GroupLayout(painelInformacoesGerais);
        painelInformacoesGerais.setLayout(painelInformacoesGeraisLayout);
        painelInformacoesGeraisLayout.setHorizontalGroup(
            painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInformacoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInformacoesGeraisLayout.createSequentialGroup()
                        .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoQuantidadePedidos)
                            .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoPagoComCredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoPagoComDinheiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoPagoComDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textoPagoComVale, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoValorQuantidadePedidos)
                            .addComponent(textoValorPagoComDinheiro)
                            .addComponent(textoValorPagoComCredito)
                            .addComponent(textoValorPagoComDebito)
                            .addComponent(textoValorPagoComVale)))
                    .addGroup(painelInformacoesGeraisLayout.createSequentialGroup()
                        .addComponent(textoFundoCaixa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoValorFundoCaixa)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelInformacoesGeraisLayout.setVerticalGroup(
            painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInformacoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFundoCaixa)
                    .addComponent(textoValorFundoCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoQuantidadePedidos)
                    .addComponent(textoValorQuantidadePedidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagoComDinheiro)
                    .addComponent(textoValorPagoComDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagoComCredito)
                    .addComponent(textoValorPagoComCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagoComDebito)
                    .addComponent(textoValorPagoComDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagoComVale)
                    .addComponent(textoValorPagoComVale))
                .addContainerGap())
        );

        painelFaturamento.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Faturamento"));

        textoValorQuantidadePedidos1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorQuantidadePedidos1.setText("R$ 0,00");

        textoDinheiro.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoDinheiro.setText("Dinheiro:");

        textoTotalFaturado.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoTotalFaturado.setText("Total Faturado:");

        textoValorDinheiro.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorDinheiro.setText("R$ 0,00");

        textoValorCredito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorCredito.setText("R$ 0,00");

        textoPagoComCredito1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoPagoComCredito1.setText("Crédito:");

        textoDebito.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoDebito.setText("Débito:");

        textoValorDebito.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorDebito.setText("R$ 0,00");

        textoValorVale.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        textoValorVale.setText("R$ 0,00");

        textoVale.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        textoVale.setText("Vale:");

        javax.swing.GroupLayout painelFaturamentoLayout = new javax.swing.GroupLayout(painelFaturamento);
        painelFaturamento.setLayout(painelFaturamentoLayout);
        painelFaturamentoLayout.setHorizontalGroup(
            painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFaturamentoLayout.createSequentialGroup()
                        .addComponent(textoTotalFaturado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textoValorQuantidadePedidos1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFaturamentoLayout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textoVale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoPagoComCredito1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoValorDinheiro)
                            .addComponent(textoValorCredito)
                            .addComponent(textoValorDebito)
                            .addComponent(textoValorVale))))
                .addContainerGap())
        );
        painelFaturamentoLayout.setVerticalGroup(
            painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFaturamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoTotalFaturado)
                    .addComponent(textoValorQuantidadePedidos1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDinheiro)
                    .addComponent(textoValorDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoPagoComCredito1)
                    .addComponent(textoValorCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDebito)
                    .addComponent(textoValorDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFaturamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoVale)
                    .addComponent(textoValorVale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelBalancoCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Balanço do Caixa"));

        javax.swing.GroupLayout painelBalancoCaixaLayout = new javax.swing.GroupLayout(painelBalancoCaixa);
        painelBalancoCaixa.setLayout(painelBalancoCaixaLayout);
        painelBalancoCaixaLayout.setHorizontalGroup(
            painelBalancoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelBalancoCaixaLayout.setVerticalGroup(
            painelBalancoCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        painelRetiradas.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Retiradas"));

        javax.swing.GroupLayout painelRetiradasLayout = new javax.swing.GroupLayout(painelRetiradas);
        painelRetiradas.setLayout(painelRetiradasLayout);
        painelRetiradasLayout.setHorizontalGroup(
            painelRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelRetiradasLayout.setVerticalGroup(
            painelRetiradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        painelDescontos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Descontos"));

        javax.swing.GroupLayout painelDescontosLayout = new javax.swing.GroupLayout(painelDescontos);
        painelDescontos.setLayout(painelDescontosLayout);
        painelDescontosLayout.setHorizontalGroup(
            painelDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelDescontosLayout.setVerticalGroup(
            painelDescontosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        painelCancelamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cancelamentos"));

        javax.swing.GroupLayout painelCancelamentosLayout = new javax.swing.GroupLayout(painelCancelamentos);
        painelCancelamentos.setLayout(painelCancelamentosLayout);
        painelCancelamentosLayout.setHorizontalGroup(
            painelCancelamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelCancelamentosLayout.setVerticalGroup(
            painelCancelamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelDetalhesCaixaLayout = new javax.swing.GroupLayout(painelDetalhesCaixa);
        painelDetalhesCaixa.setLayout(painelDetalhesCaixaLayout);
        painelDetalhesCaixaLayout.setHorizontalGroup(
            painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDetalhesCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDetalhesCaixaLayout.createSequentialGroup()
                        .addComponent(painelBalancoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(painelRetiradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))
                    .addGroup(painelDetalhesCaixaLayout.createSequentialGroup()
                        .addGroup(painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDetalhesCaixaLayout.createSequentialGroup()
                                .addComponent(painelInformacoesGerais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelFaturamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDetalhesCaixaLayout.createSequentialGroup()
                                .addComponent(painelDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelCancelamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        painelDetalhesCaixaLayout.setVerticalGroup(
            painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDetalhesCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelFaturamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelInformacoesGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelRetiradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelBalancoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDetalhesCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDescontos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(painelCancelamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botaoCancelarIngrediente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        botaoCancelarIngrediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaoCancelarIngrediente.setText("Cancelar Cadastro");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/check-32.png"))); // NOI18N
        jButton1.setText("Reimprimir Relatório de Fechamento de Caixa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoCancelarIngrediente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCancelarIngrediente)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelBuscarCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelDetalhesCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelDetalhesCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelBuscarCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public JButton getBotaoCancelarIngrediente() {
        return botaoCancelarIngrediente;
    }

    public void setBotaoCancelarIngrediente(JButton botaoCancelarIngrediente) {
        this.botaoCancelarIngrediente = botaoCancelarIngrediente;
    }

    public JButton getBotaoProcurarIngrediente() {
        return botaoProcurarCaixa;
    }

    public void setBotaoProcurarIngrediente(JButton botaoProcurarIngrediente) {
        this.botaoProcurarCaixa = botaoProcurarIngrediente;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarIngrediente;
    private javax.swing.JButton botaoProcurarCaixa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comboBoxCaixasAbertos;
    private com.toedter.calendar.JDateChooser dateChooserDataAberturaCaixa;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel painelBalancoCaixa;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelBuscarCaixa;
    private javax.swing.JPanel painelCancelamentos;
    private javax.swing.JPanel painelDescontos;
    private javax.swing.JPanel painelDetalhesCaixa;
    private javax.swing.JPanel painelFaturamento;
    private javax.swing.JPanel painelInformacoesGerais;
    private javax.swing.JPanel painelRetiradas;
    private javax.swing.JScrollPane painelScrollCaixasEncontrados;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JSeparator separadorBuscaResultado;
    private javax.swing.JTable tabelaCaixasEncontrados;
    private javax.swing.JLabel textoCaixasAbertos;
    private javax.swing.JLabel textoCliqueParaEditar;
    private javax.swing.JLabel textoDataAberturaCaixa;
    private javax.swing.JLabel textoDebito;
    private javax.swing.JLabel textoDinheiro;
    private javax.swing.JLabel textoFundoCaixa;
    private javax.swing.JLabel textoIconeVisualizarCaixas;
    private javax.swing.JLabel textoPagoComCredito;
    private javax.swing.JLabel textoPagoComCredito1;
    private javax.swing.JLabel textoPagoComDebito;
    private javax.swing.JLabel textoPagoComDinheiro;
    private javax.swing.JLabel textoPagoComVale;
    private javax.swing.JLabel textoPreencherDados;
    private javax.swing.JLabel textoQuantidadePedidos;
    private javax.swing.JLabel textoTotalFaturado;
    private javax.swing.JLabel textoVale;
    private javax.swing.JLabel textoValorCredito;
    private javax.swing.JLabel textoValorDebito;
    private javax.swing.JLabel textoValorDinheiro;
    private javax.swing.JLabel textoValorFundoCaixa;
    private javax.swing.JLabel textoValorPagoComCredito;
    private javax.swing.JLabel textoValorPagoComDebito;
    private javax.swing.JLabel textoValorPagoComDinheiro;
    private javax.swing.JLabel textoValorPagoComVale;
    private javax.swing.JLabel textoValorQuantidadePedidos;
    private javax.swing.JLabel textoValorQuantidadePedidos1;
    private javax.swing.JLabel textoValorVale;
    private javax.swing.JLabel textoVisualizarCaixas;
    // End of variables declaration//GEN-END:variables
}
