/*
 * The MIT License
 *
 * Copyright 2014 Tiago.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package com.au.gui;

/**
 *
 * @author Tiago
 */
public class TelaFechamentoCaixa extends javax.swing.JDialog {

    /**
     * Creates new form TelaFechamentoCaixa
     */
    public TelaFechamentoCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSuperior = new javax.swing.JPanel();
        textoFechamentoDeCaixa = new javax.swing.JLabel();
        painelDinheiroEmCaixa = new javax.swing.JPanel();
        textoMoedaCincoCentavos = new javax.swing.JLabel();
        campoMoedaCincoCentavos = new javax.swing.JTextField();
        textoMoedaDezCentavos = new javax.swing.JLabel();
        campoMoedaDezCentavos = new javax.swing.JTextField();
        textoMoedaVinteCintoCentavos = new javax.swing.JLabel();
        campoMoedaVinteCincoCentavos = new javax.swing.JTextField();
        textoMoedaCinquentaCentavos = new javax.swing.JLabel();
        campoMoedaCinquentaCentavos = new javax.swing.JTextField();
        textoMoedaUmReal = new javax.swing.JLabel();
        campoMoedaUmReal = new javax.swing.JTextField();
        textoCedulaDoisReais = new javax.swing.JLabel();
        campoCedulaDoisReais = new javax.swing.JTextField();
        textoCedulaCincoReais = new javax.swing.JLabel();
        campoCedulaCincoReais = new javax.swing.JTextField();
        textoCedulaDezReais = new javax.swing.JLabel();
        campoCedulaDezReais = new javax.swing.JTextField();
        textoCedulaVinteReais = new javax.swing.JLabel();
        campoCedulaVinteReais = new javax.swing.JTextField();
        textoCedulaCinquentaReais = new javax.swing.JLabel();
        campoCedulaCinquentaReais = new javax.swing.JTextField();
        textoCedulaCemReais = new javax.swing.JLabel();
        campoCedulaCemReais = new javax.swing.JTextField();
        textoDinheiroTotalEmCaixa = new javax.swing.JLabel();
        textoValorTotalEmCaixa = new javax.swing.JLabel();
        textoMoedas = new javax.swing.JLabel();
        textoCedulas = new javax.swing.JLabel();
        painelFaturamentos = new javax.swing.JPanel();
        textoValoresFaturados = new javax.swing.JLabel();
        textoDinheiro = new javax.swing.JLabel();
        textoCartaoDeCredito = new javax.swing.JLabel();
        textoCartaoDeDebito = new javax.swing.JLabel();
        textoValeRefeicao = new javax.swing.JLabel();
        textoValorDinheiro = new javax.swing.JLabel();
        textoValorCartaoDeCredito = new javax.swing.JLabel();
        textoValorCartaoDeDebito = new javax.swing.JLabel();
        textoValorValeRefeicao = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        textoValorTotalFaturado = new javax.swing.JLabel();
        botaoConfirmarFechamentoDeCaixa = new javax.swing.JButton();
        botaoCancelarFechamentoDeCaixa = new javax.swing.JButton();
        painelReducoes = new javax.swing.JPanel();
        textoFundoDeCaixa = new javax.swing.JLabel();
        textoDespesas = new javax.swing.JLabel();
        textoValorFundoDeCaixa = new javax.swing.JLabel();
        textoValorDespesas = new javax.swing.JLabel();
        textoTotalDeReducoes = new javax.swing.JLabel();
        textoValorTotalDeReducoes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema Pastelão - Fechamento de Caixa");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        painelSuperior.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        textoFechamentoDeCaixa.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        textoFechamentoDeCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoFechamentoDeCaixa.setText("Fechamento de Caixa");

        javax.swing.GroupLayout painelSuperiorLayout = new javax.swing.GroupLayout(painelSuperior);
        painelSuperior.setLayout(painelSuperiorLayout);
        painelSuperiorLayout.setHorizontalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoFechamentoDeCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelSuperiorLayout.setVerticalGroup(
            painelSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoFechamentoDeCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelDinheiroEmCaixa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dinheiro em Caixa"));

        textoMoedaCincoCentavos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMoedaCincoCentavos.setText("0.05:");

        campoMoedaCincoCentavos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoMoedaDezCentavos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMoedaDezCentavos.setText("0.10:");

        campoMoedaDezCentavos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoMoedaVinteCintoCentavos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMoedaVinteCintoCentavos.setText("0.25:");

        campoMoedaVinteCincoCentavos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoMoedaCinquentaCentavos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMoedaCinquentaCentavos.setText("0.50:");

        campoMoedaCinquentaCentavos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoMoedaUmReal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoMoedaUmReal.setText("1.00:");

        campoMoedaUmReal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaDoisReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaDoisReais.setText("2.00:");

        campoCedulaDoisReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaCincoReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaCincoReais.setText("5.00:");

        campoCedulaCincoReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaDezReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaDezReais.setText("10.00:");

        campoCedulaDezReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaVinteReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaVinteReais.setText("20.00:");

        campoCedulaVinteReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaCinquentaReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaCinquentaReais.setText("50.00:");

        campoCedulaCinquentaReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoCedulaCemReais.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoCedulaCemReais.setText("100.00:");

        campoCedulaCemReais.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        textoDinheiroTotalEmCaixa.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        textoDinheiroTotalEmCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoDinheiroTotalEmCaixa.setText("Dinheiro Total em Caixa:");

        textoValorTotalEmCaixa.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textoValorTotalEmCaixa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorTotalEmCaixa.setText("R$: 0000.00");

        textoMoedas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoMoedas.setText("Moedas:");

        textoCedulas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textoCedulas.setText("Cédulas:");

        javax.swing.GroupLayout painelDinheiroEmCaixaLayout = new javax.swing.GroupLayout(painelDinheiroEmCaixa);
        painelDinheiroEmCaixa.setLayout(painelDinheiroEmCaixaLayout);
        painelDinheiroEmCaixaLayout.setHorizontalGroup(
            painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDinheiroTotalEmCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorTotalEmCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textoMoedaDezCentavos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoMoedaCincoCentavos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoMoedaVinteCintoCentavos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoMoedaCinquentaCentavos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoMoedaUmReal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoMoedaCincoCentavos)
                                    .addComponent(campoMoedaDezCentavos)
                                    .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(campoMoedaUmReal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(campoMoedaCinquentaCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(campoMoedaVinteCincoCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(textoMoedas))
                        .addGap(18, 18, 18)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addComponent(textoCedulaCemReais)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedulaCemReais, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textoCedulas)
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textoCedulaDoisReais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textoCedulaCincoReais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoCedulaCincoReais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoCedulaDoisReais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addComponent(textoCedulaDezReais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedulaDezReais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addComponent(textoCedulaVinteReais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedulaVinteReais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                                .addComponent(textoCedulaCinquentaReais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(campoCedulaCinquentaReais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        painelDinheiroEmCaixaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {textoCedulaCemReais, textoCedulaCincoReais, textoCedulaCinquentaReais, textoCedulaDezReais, textoCedulaDoisReais, textoCedulaVinteReais, textoMoedaCincoCentavos, textoMoedaCinquentaCentavos, textoMoedaDezCentavos, textoMoedaUmReal, textoMoedaVinteCintoCentavos});

        painelDinheiroEmCaixaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {campoCedulaCemReais, campoCedulaCincoReais, campoCedulaCinquentaReais, campoCedulaDezReais, campoCedulaDoisReais, campoCedulaVinteReais, campoMoedaCincoCentavos, campoMoedaCinquentaCentavos, campoMoedaDezCentavos, campoMoedaUmReal, campoMoedaVinteCincoCentavos});

        painelDinheiroEmCaixaLayout.setVerticalGroup(
            painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                        .addComponent(textoMoedas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoMoedaCincoCentavos)
                            .addComponent(campoMoedaCincoCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoMoedaDezCentavos)
                            .addComponent(campoMoedaDezCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoMoedaVinteCintoCentavos)
                            .addComponent(campoMoedaVinteCincoCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoMoedaCinquentaCentavos)
                            .addComponent(campoMoedaCinquentaCentavos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoMoedaUmReal)
                            .addComponent(campoMoedaUmReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelDinheiroEmCaixaLayout.createSequentialGroup()
                        .addComponent(textoCedulas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoCedulaDoisReais)
                            .addComponent(campoCedulaDoisReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCedulaCincoReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textoCedulaCincoReais))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCedulaDezReais)
                            .addComponent(campoCedulaDezReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCedulaVinteReais)
                            .addComponent(campoCedulaVinteReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCedulaCinquentaReais)
                            .addComponent(campoCedulaCinquentaReais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelDinheiroEmCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoCedulaCemReais)
                            .addComponent(campoCedulaCemReais, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoDinheiroTotalEmCaixa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoValorTotalEmCaixa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDinheiroEmCaixaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {campoCedulaCemReais, campoCedulaCincoReais, campoCedulaCinquentaReais, campoCedulaDezReais, campoCedulaDoisReais, campoCedulaVinteReais, campoMoedaCincoCentavos, campoMoedaCinquentaCentavos, campoMoedaDezCentavos, campoMoedaUmReal, campoMoedaVinteCincoCentavos, textoCedulaCemReais});

        painelFaturamentos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Faturamentos"));

        textoValoresFaturados.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        textoValoresFaturados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValoresFaturados.setText("Valores faturados por modalidade:");

        textoDinheiro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textoDinheiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/banknotes-64.png"))); // NOI18N
        textoDinheiro.setText(" Dinheiro:");

        textoCartaoDeCredito.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textoCartaoDeCredito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/mastercard-64.png"))); // NOI18N
        textoCartaoDeCredito.setText(" Cartão de Crédito:");

        textoCartaoDeDebito.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textoCartaoDeDebito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/bank_cards-64.png"))); // NOI18N
        textoCartaoDeDebito.setText(" Cartão de Débito:");

        textoValeRefeicao.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        textoValeRefeicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/barcode-64.png"))); // NOI18N
        textoValeRefeicao.setText(" Vale Refeição:");

        textoValorDinheiro.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoValorDinheiro.setText("R$: 000.00");

        textoValorCartaoDeCredito.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoValorCartaoDeCredito.setText("R$: 000.00");

        textoValorCartaoDeDebito.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoValorCartaoDeDebito.setText("R$: 000.00");

        textoValorValeRefeicao.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoValorValeRefeicao.setText("R$: 000.00");

        textoValorTotalFaturado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        textoValorTotalFaturado.setText("TOTAL FATURADO: R$ 00000.00");

        javax.swing.GroupLayout painelFaturamentosLayout = new javax.swing.GroupLayout(painelFaturamentos);
        painelFaturamentos.setLayout(painelFaturamentosLayout);
        painelFaturamentosLayout.setHorizontalGroup(
            painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(painelFaturamentosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoValoresFaturados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorTotalFaturado, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                    .addGroup(painelFaturamentosLayout.createSequentialGroup()
                        .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoCartaoDeCredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoValeRefeicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoCartaoDeDebito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDinheiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoValorDinheiro)
                            .addComponent(textoValorCartaoDeCredito)
                            .addComponent(textoValorCartaoDeDebito)
                            .addComponent(textoValorValeRefeicao))
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        painelFaturamentosLayout.setVerticalGroup(
            painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFaturamentosLayout.createSequentialGroup()
                .addComponent(textoValoresFaturados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDinheiro)
                    .addComponent(textoValorDinheiro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCartaoDeCredito)
                    .addComponent(textoValorCartaoDeCredito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCartaoDeDebito)
                    .addComponent(textoValorCartaoDeDebito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelFaturamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoValeRefeicao)
                    .addComponent(textoValorValeRefeicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoValorTotalFaturado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelFaturamentosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoDinheiro, textoValorDinheiro});

        painelFaturamentosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoCartaoDeCredito, textoValorCartaoDeCredito});

        painelFaturamentosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoCartaoDeDebito, textoValorCartaoDeDebito});

        painelFaturamentosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {textoValeRefeicao, textoValorValeRefeicao});

        botaoConfirmarFechamentoDeCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoConfirmarFechamentoDeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/ok-32.png"))); // NOI18N
        botaoConfirmarFechamentoDeCaixa.setText("Confirmar Fechamento de Caixa");

        botaoCancelarFechamentoDeCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botaoCancelarFechamentoDeCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/au/resources/icons/cancel-32.png"))); // NOI18N
        botaoCancelarFechamentoDeCaixa.setText("Cancelar Fechamento de Caixa");

        painelReducoes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Reduções"));

        textoFundoDeCaixa.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        textoFundoDeCaixa.setText("Fundo de caixa:");

        textoDespesas.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        textoDespesas.setText("Despesas:");

        textoValorFundoDeCaixa.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textoValorFundoDeCaixa.setText("R$: 000.00");

        textoValorDespesas.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textoValorDespesas.setText("R$: 0000.00");

        textoTotalDeReducoes.setFont(new java.awt.Font("Tahoma", 2, 20)); // NOI18N
        textoTotalDeReducoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoTotalDeReducoes.setText("Total de Reduções:");

        textoValorTotalDeReducoes.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        textoValorTotalDeReducoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoValorTotalDeReducoes.setText("R$: 0000.00");

        javax.swing.GroupLayout painelReducoesLayout = new javax.swing.GroupLayout(painelReducoes);
        painelReducoes.setLayout(painelReducoesLayout);
        painelReducoesLayout.setHorizontalGroup(
            painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelReducoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelReducoesLayout.createSequentialGroup()
                        .addGroup(painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textoFundoDeCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textoDespesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelReducoesLayout.createSequentialGroup()
                                .addComponent(textoValorDespesas)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelReducoesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(textoValorFundoDeCaixa))))
                    .addComponent(textoTotalDeReducoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textoValorTotalDeReducoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelReducoesLayout.setVerticalGroup(
            painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelReducoesLayout.createSequentialGroup()
                .addGroup(painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoFundoDeCaixa)
                    .addComponent(textoValorFundoDeCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelReducoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoDespesas)
                    .addComponent(textoValorDespesas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoTotalDeReducoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textoValorTotalDeReducoes)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelDinheiroEmCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelReducoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(painelFaturamentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(botaoCancelarFechamentoDeCaixa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoConfirmarFechamentoDeCaixa)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelFaturamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botaoCancelarFechamentoDeCaixa)
                            .addComponent(botaoConfirmarFechamentoDeCaixa)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelDinheiroEmCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelReducoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFechamentoCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaFechamentoCaixa dialog = new TelaFechamentoCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelarFechamentoDeCaixa;
    private javax.swing.JButton botaoConfirmarFechamentoDeCaixa;
    private javax.swing.JTextField campoCedulaCemReais;
    private javax.swing.JTextField campoCedulaCincoReais;
    private javax.swing.JTextField campoCedulaCinquentaReais;
    private javax.swing.JTextField campoCedulaDezReais;
    private javax.swing.JTextField campoCedulaDoisReais;
    private javax.swing.JTextField campoCedulaVinteReais;
    private javax.swing.JTextField campoMoedaCincoCentavos;
    private javax.swing.JTextField campoMoedaCinquentaCentavos;
    private javax.swing.JTextField campoMoedaDezCentavos;
    private javax.swing.JTextField campoMoedaUmReal;
    private javax.swing.JTextField campoMoedaVinteCincoCentavos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painelDinheiroEmCaixa;
    private javax.swing.JPanel painelFaturamentos;
    private javax.swing.JPanel painelReducoes;
    private javax.swing.JPanel painelSuperior;
    private javax.swing.JLabel textoCartaoDeCredito;
    private javax.swing.JLabel textoCartaoDeDebito;
    private javax.swing.JLabel textoCedulaCemReais;
    private javax.swing.JLabel textoCedulaCincoReais;
    private javax.swing.JLabel textoCedulaCinquentaReais;
    private javax.swing.JLabel textoCedulaDezReais;
    private javax.swing.JLabel textoCedulaDoisReais;
    private javax.swing.JLabel textoCedulaVinteReais;
    private javax.swing.JLabel textoCedulas;
    private javax.swing.JLabel textoDespesas;
    private javax.swing.JLabel textoDinheiro;
    private javax.swing.JLabel textoDinheiroTotalEmCaixa;
    private javax.swing.JLabel textoFechamentoDeCaixa;
    private javax.swing.JLabel textoFundoDeCaixa;
    private javax.swing.JLabel textoMoedaCincoCentavos;
    private javax.swing.JLabel textoMoedaCinquentaCentavos;
    private javax.swing.JLabel textoMoedaDezCentavos;
    private javax.swing.JLabel textoMoedaUmReal;
    private javax.swing.JLabel textoMoedaVinteCintoCentavos;
    private javax.swing.JLabel textoMoedas;
    private javax.swing.JLabel textoTotalDeReducoes;
    private javax.swing.JLabel textoValeRefeicao;
    private javax.swing.JLabel textoValorCartaoDeCredito;
    private javax.swing.JLabel textoValorCartaoDeDebito;
    private javax.swing.JLabel textoValorDespesas;
    private javax.swing.JLabel textoValorDinheiro;
    private javax.swing.JLabel textoValorFundoDeCaixa;
    private javax.swing.JLabel textoValorTotalDeReducoes;
    private javax.swing.JLabel textoValorTotalEmCaixa;
    private javax.swing.JLabel textoValorTotalFaturado;
    private javax.swing.JLabel textoValorValeRefeicao;
    private javax.swing.JLabel textoValoresFaturados;
    // End of variables declaration//GEN-END:variables
}
