package com.au.pojo;
// Generated 26/03/2014 01:12:55 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Ingrediente generated by hbm2java
 */
public class Ingrediente  implements java.io.Serializable {


     private Integer idIng;
     private String descIng;
     private double valorIng;
     private Set notaingredientes = new HashSet(0);
     private Set produtos = new HashSet(0);

    public Ingrediente() {
    }

	
    public Ingrediente(String descIng, double valorIng) {
        this.descIng = descIng;
        this.valorIng = valorIng;
    }
    public Ingrediente(String descIng, double valorIng, Set notaingredientes, Set produtos) {
       this.descIng = descIng;
       this.valorIng = valorIng;
       this.notaingredientes = notaingredientes;
       this.produtos = produtos;
    }
   
    public Integer getIdIng() {
        return this.idIng;
    }
    
    public void setIdIng(Integer idIng) {
        this.idIng = idIng;
    }
    public String getDescIng() {
        return this.descIng;
    }
    
    public void setDescIng(String descIng) {
        this.descIng = descIng;
    }
    public double getValorIng() {
        return this.valorIng;
    }
    
    public void setValorIng(double valorIng) {
        this.valorIng = valorIng;
    }
    public Set getNotaingredientes() {
        return this.notaingredientes;
    }
    
    public void setNotaingredientes(Set notaingredientes) {
        this.notaingredientes = notaingredientes;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


