package com.au.pojo;
// Generated 26/03/2014 01:12:55 by Hibernate Tools 3.6.0



/**
 * NotaingredienteId generated by hbm2java
 */
public class NotaingredienteId  implements java.io.Serializable {


     private int idIng;
     private int idNota;

    public NotaingredienteId() {
    }

    public NotaingredienteId(int idIng, int idNota) {
       this.idIng = idIng;
       this.idNota = idNota;
    }
   
    public int getIdIng() {
        return this.idIng;
    }
    
    public void setIdIng(int idIng) {
        this.idIng = idIng;
    }
    public int getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(int idNota) {
        this.idNota = idNota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotaingredienteId) ) return false;
		 NotaingredienteId castOther = ( NotaingredienteId ) other; 
         
		 return (this.getIdIng()==castOther.getIdIng())
 && (this.getIdNota()==castOther.getIdNota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdIng();
         result = 37 * result + this.getIdNota();
         return result;
   }   


}


