package com.au.pojo;
// Generated 30/03/2014 04:22:00 by Hibernate Tools 3.6.0



/**
 * NotaprodutoId generated by hbm2java
 */
public class NotaprodutoId  implements java.io.Serializable {


     private int idProd;
     private int idNota;

    public NotaprodutoId() {
    }

    public NotaprodutoId(int idProd, int idNota) {
       this.idProd = idProd;
       this.idNota = idNota;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public int getIdNota() {
        return this.idNota;
    }
    
    public void setIdNota(int idNota) {
        this.idNota = idNota;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotaprodutoId) ) return false;
		 NotaprodutoId castOther = ( NotaprodutoId ) other; 
         
		 return (this.getIdProd()==castOther.getIdProd())
 && (this.getIdNota()==castOther.getIdNota());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProd();
         result = 37 * result + this.getIdNota();
         return result;
   }   


}


