package com.au.pojo;
// Generated 26/03/2014 01:12:55 by Hibernate Tools 3.6.0



/**
 * Notaingrediente generated by hbm2java
 */
public class Notaingrediente  implements java.io.Serializable {


     private NotaingredienteId id;
     private Notafiscal notafiscal;
     private Ingrediente ingrediente;
     private int qtdNota;
     private double valorNota;

    public Notaingrediente() {
    }

    public Notaingrediente(NotaingredienteId id, Notafiscal notafiscal, Ingrediente ingrediente, int qtdNota, double valorNota) {
       this.id = id;
       this.notafiscal = notafiscal;
       this.ingrediente = ingrediente;
       this.qtdNota = qtdNota;
       this.valorNota = valorNota;
    }
   
    public NotaingredienteId getId() {
        return this.id;
    }
    
    public void setId(NotaingredienteId id) {
        this.id = id;
    }
    public Notafiscal getNotafiscal() {
        return this.notafiscal;
    }
    
    public void setNotafiscal(Notafiscal notafiscal) {
        this.notafiscal = notafiscal;
    }
    public Ingrediente getIngrediente() {
        return this.ingrediente;
    }
    
    public void setIngrediente(Ingrediente ingrediente) {
        this.ingrediente = ingrediente;
    }
    public int getQtdNota() {
        return this.qtdNota;
    }
    
    public void setQtdNota(int qtdNota) {
        this.qtdNota = qtdNota;
    }
    public double getValorNota() {
        return this.valorNota;
    }
    
    public void setValorNota(double valorNota) {
        this.valorNota = valorNota;
    }




}


