package com.au.pojo;
// Generated 30/03/2014 04:22:00 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int idProd;
     private Fornecedor fornecedor;
     private String descProd;
     private double valorProd;
     private int qtdProd;
     private String codBarras;
     private boolean eindustrializado;
     private Set itempedidos = new HashSet(0);
     private Set ingredientes = new HashSet(0);
     private Set notaprodutos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int idProd, Fornecedor fornecedor, String descProd, double valorProd, int qtdProd, boolean eindustrializado) {
        this.idProd = idProd;
        this.fornecedor = fornecedor;
        this.descProd = descProd;
        this.valorProd = valorProd;
        this.qtdProd = qtdProd;
        this.eindustrializado = eindustrializado;
    }
    public Produto(int idProd, Fornecedor fornecedor, String descProd, double valorProd, int qtdProd, String codBarras, boolean eindustrializado, Set itempedidos, Set ingredientes, Set notaprodutos) {
       this.idProd = idProd;
       this.fornecedor = fornecedor;
       this.descProd = descProd;
       this.valorProd = valorProd;
       this.qtdProd = qtdProd;
       this.codBarras = codBarras;
       this.eindustrializado = eindustrializado;
       this.itempedidos = itempedidos;
       this.ingredientes = ingredientes;
       this.notaprodutos = notaprodutos;
    }
   
    public int getIdProd() {
        return this.idProd;
    }
    
    public void setIdProd(int idProd) {
        this.idProd = idProd;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public String getDescProd() {
        return this.descProd;
    }
    
    public void setDescProd(String descProd) {
        this.descProd = descProd;
    }
    public double getValorProd() {
        return this.valorProd;
    }
    
    public void setValorProd(double valorProd) {
        this.valorProd = valorProd;
    }
    public int getQtdProd() {
        return this.qtdProd;
    }
    
    public void setQtdProd(int qtdProd) {
        this.qtdProd = qtdProd;
    }
    public String getCodBarras() {
        return this.codBarras;
    }
    
    public void setCodBarras(String codBarras) {
        this.codBarras = codBarras;
    }
    public boolean isEindustrializado() {
        return this.eindustrializado;
    }
    
    public void setEindustrializado(boolean eindustrializado) {
        this.eindustrializado = eindustrializado;
    }
    public Set getItempedidos() {
        return this.itempedidos;
    }
    
    public void setItempedidos(Set itempedidos) {
        this.itempedidos = itempedidos;
    }
    public Set getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Set ingredientes) {
        this.ingredientes = ingredientes;
    }
    public Set getNotaprodutos() {
        return this.notaprodutos;
    }
    
    public void setNotaprodutos(Set notaprodutos) {
        this.notaprodutos = notaprodutos;
    }




}


